
/////////////////////////////////////////////////////////////////////////////////
// Extrai do ROUTE_ID o nome da Contabilidade
/////////////////////////////////////////////////////////////////////////////////
private String getNomeContabilidadeWorkflow() throws Exception {
    String contabilidade = INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf("."));

    return contabilidade;
}

/////////////////////////////////////////////////////////////////////////////////
////////////////////  ////   WORKFLOW  OTW (Endpoint A)    ////  ////////////////
/////////////////////////////////////////////////////////////////////////////////
JSONArray runWorkflowEndpointA(InoutLogger logger) throws Exception {
    JSONArray records    = new JSONArray();

    SysProperties routesProperties = SysProperties.getInstance();
    SysProperties contabilidadesAtivas = SysProperties.getInstance();
    SysProperties props  = SysProperties.getInstance();
    SysProperties props2 = SysProperties.getInstance();
	SysProperties propsOtt = SysProperties.getInstance();

	propsOtt.load("contabil/Ottimizza/contabil.properties");
	
	ConnectorConfig config = new ConnectorConfig();
	config.setUsername("fabrica@ottimizza.com.br");
	config.setPassword("ottimizza@123HU4ssqt1HCiLyCzj6QStgteM2");
	config.setTraceMessage(false);
	
	//config.setUsername("adm@ottimizza.com.br");
	//config.setPassword("oic@3333222YXZRHYLH8cxrchPu0rjyGH1j8");
	//config.setTraceMessage(true);

    String servDinamic = "";
	try{
		servDinamic = buscaServidor(logger).toLowerCase();
		if(servDinamic.equals("")) servDinamic = "zeus";
	}catch(Exception e){
		logger.logInfo("ERRO AO BUSCAR - "+e.getMessage());
        servDinamic = "zeus";
	}
    
	double tempoInicial = System.currentTimeMillis();
	boolean rodouRota = false;

    String arquivoGrande = "";
    String jSdir = "";
    String operacao = "";

    boolean converteu = false;

    DataBase dbIOContOtt = null;
    double sizeLimit = 4;               //tamanho maximo processavel                        //-
    // if (contabilidade.toUpperCase().contains("TECOLMG")) sizeLimit = 40; // #Fabrica(2019-07-24) @Becker
    sizeLimit = sizeLimit * (Math.pow(1024,2)); //MiB                                       //-

    String extensaoArquivo  = "";
    String diretorioArquivo = "";

    boolean rotasOk = false;
    String filename = "";
    String filenameCanal = "";
    String extensaoSuportada = ".csv.xlsx.txt.ofx.dat.pdf.prn.ret.dp1.dp2.dp9.omc.html.ret";

    try {
        // tenta carregar propriedades de rotas.
        try { routesProperties.load(String.format("/contabil/ottimizza/routes.properties", RouteEngine.INOUT_HOME));
            } catch (Exception ex) { logger.logDebug("Nao foi poss?iel ler arquivo de propriedades.");
            }
		// tenta carregar propriedades de contabilidades Ativas.
        try { contabilidadesAtivas.load(String.format("/contabil/ottimizza/contabilidadesativas.properties", RouteEngine.INOUT_HOME));
            } catch (Exception ex) { logger.logDebug("Nao foi poss?iel ler arquivo de propriedades.");
            }

        File dirInoutContabil = new File(String.format("%s/contabil/", RouteEngine.INOUT_HOME));

		if (dbIOContOtt == null) {
			dbIOContOtt = connectIOContabil(propsOtt, logger);
		}
		
		String idFila = "";

		JSONObject objetoFila = buscaDiretorioArquivoProcessado(dbIOContOtt, logger);
        if (objetoFila.has("DIRETORIO")) {
			diretorioArquivo = objetoFila.optString("DIRETORIO");
			idFila = objetoFila.optString("ID");
		} else {
			logger.logInfo("Tentou ler duplicado");
			return new JSONArray();
		}
		// if (true) return new JSONArray();
		postStatus("S1", INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")), "Ocioso", "Nada Pendente", "Sem Arquivo Para Processar", INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")));
  

		logger.logInfo("LENDO ARQV " + diretorioArquivo + " | " + idFila);

		if (!diretorioArquivo.equals("")) {
			if (dirInoutContabil.exists()) {
                
                String contabilidade = cutString(diretorioArquivo, "contabil/", "/");

                String empresa = diretorioArquivo.substring(0, diretorioArquivo.lastIndexOf("/"));

                
                empresa = cutString(empresa, 0, empresa.lastIndexOf("/"));
                empresa = cutString(empresa, empresa.lastIndexOf("/")+1);

				// Empresas do tipo Bussola sao agora processadas em um workflow especifico e por isto ignoradas no OIC
				if (empresa.toUpperCase().startsWith("BUSSOLA") && !empresa.toUpperCase().endsWith("BUSSOLA")) return records;

                props.load("contabil/" + contabilidade + "/contabil.properties");
                props2.load("contabil/" + contabilidade + "/empresa.properties");

                String dirName = RouteEngine.INOUT_HOME + "/contabil/" + contabilidade + "/";
                String dirNameW = RouteEngine.INOUT_HOME + "/contabil/" + INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) + "/";
                String dirRouteName = RouteEngine.INOUT_HOME + "/routes/" + contabilidade;

                String versaoPlataforma = props.get("VERSAO_PLATAFORMA");
                String versaoOtzWebApp = "02_Conecta_Via_Portal_Ottimizza";
                String fornecedorUnico = props.get("FORNECEDOR_UNICO");


                String oicContabil  = props.get("OIC_LIBERADO");

                String diretorioConversorExcel = "C:/Conversor/Excel";
                File file2 = new File(diretorioConversorExcel);
                
                File[] files = file2.listFiles();

                String oicEmpresa = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_LIBERA_OIC");


                if (FileUtil.dirHasFiles(diretorioConversorExcel)) {
                    for (File fl: files) {
                        if (fl.getAbsolutePath().contains("aba[") && (fl.getAbsolutePath().toUpperCase().contains("PAGAR") || fl.getAbsolutePath().toUpperCase().contains("RECEBER")) && fl.getAbsolutePath().contains("#") && fl.getAbsolutePath().contains("_ancora_") && fl.length() > 0){
                            String diretorioArquivoCsv = "C:/inout/contabil/";
                            String testeCsv = "";
                            String abaCsv = "";
                            String contabilidadeCsv = "";
                            String empresaCsv = "";
                            
                            // if (fl.getAbsolutePath().toUpperCase().contains("MICALI")) continue;
                            
                            long time1 = fl.lastModified();
                            double timeDouble = (double) time1;
                            
                            double times = (System.currentTimeMillis() - timeDouble) / 1000;
                            
                            // int longTime1 = time1.intValue();
                            // logger.logInfo("ULTIMA MODIFICACAO " + fl.getAbsolutePath() + " | " + time1 + " | " + System.currentTimeMillis());
                            // \("ULTIMA MODIFICACAOTEMPOS " + times);
            
                            if (times > 10) {
                            
                                if (fl.getAbsolutePath().contains("_pagar_")) {
                                    try {
                                        abaCsv = cutString(fl.getAbsolutePath(),"aba[","_pagar_");
                                        testeCsv = cutString(fl.getAbsolutePath(), "_pagar_");
                                        contabilidadeCsv = testeCsv.substring(0, testeCsv.indexOf("_"));
                                        empresaCsv = testeCsv.substring(testeCsv.indexOf("_")+1);
                                        empresaCsv = empresaCsv.substring(0, empresaCsv.indexOf("_ancora_"));
                                        diretorioArquivoCsv += contabilidadeCsv + "/" + empresaCsv + "/APagar";
                                    } catch (Exception e) {
                                        logger.logInfo("ERRO AO CORTAR ARQUIVO " + e.getMessage());
                                    }
                                }
                                else if (fl.getAbsolutePath().contains("_receber_")) {
                                    try {
                                        abaCsv = cutString(fl.getAbsolutePath(),"aba[","_receber_");
                                        testeCsv = cutString(fl.getAbsolutePath(), "_receber_");
                                        contabilidadeCsv = testeCsv.substring(0, testeCsv.indexOf("_"));
                                        empresaCsv = testeCsv.substring(testeCsv.indexOf("_")+1);
                                        
                                        // logger.logInfo("ECS " + empresaCsv);
                                        empresaCsv = empresaCsv.substring(0, empresaCsv.indexOf("_ancora_"));
                                        // logger.logInfo("ECS3" + empresaCsv);
                                        diretorioArquivoCsv += contabilidadeCsv + "/" + empresaCsv + "/AReceber";
                                    } catch (Exception e) {
                                        logger.logInfo("ERRO AO CORTAR ARQUIVO " + e.getMessage());
                                    }
                                }
                                String arquivoDeployStr = "";
                                try {
                                    arquivoDeployStr = "aba_"+abaCsv.replace("[","").replace("]","")+"_"+fl.getAbsolutePath().substring(fl.getAbsolutePath().indexOf("_ancora_")+8);
                                    //arquivoDeployStr = fl.getAbsolutePath().substring(fl.getAbsolutePath().indexOf("_ancora_")+8);
                                } catch (Exception e) {
                                    logger.logInfo("NAOCRIOURODACONVERSOR " + e.getMessage());
                                }
                                            
                                if (!arquivoDeployStr.equals("")) {
                                    File arquivoDeploy  = new File(diretorioArquivoCsv + "/" + arquivoDeployStr);
                                    // DHF C:\Conversor\Excel\aba[0]_PAGAR_Micalicontabil_Velasquesamaraldall_ott_oud__id4418_pago0218_modelo 05-2022.csv RODACONVERSOR
                                    FileUtil.copyFolder(fl, arquivoDeploy);
                                
                                    try { 
                                        FileUtil.deleteFile(fl);
                                    } catch (Exception XX) {}
                                }
                            }
                        
                            continue;
                        }
                    }
                }


                if (!contabilidade.equals("")) {
                    ///////////////////////////////////////////////////////////
                    // DEPARA /////////////////////////////////////////////////
                    ///////////////////////////////////////////////////////////
                    operacao = "DePara";
                    String diretorioDePara = cutString(diretorioArquivo, 0, diretorioArquivo.lastIndexOf("/"));
                    diretorioDePara = cutString(diretorioDePara, 0, diretorioDePara.lastIndexOf("/"));
        
                    diretorioDePara += "/DePara";
                    File file2DePara = new File(diretorioDePara);
                    File[] filesDePara = file2DePara.listFiles();
                    
                    logger.logInfo("DDP " + diretorioDePara);
                    
                    try {
                        if (FileUtil.dirHasFiles(diretorioDePara)) {
                            for (File fileDePara: filesDePara) {

                                if(fileDePara.length() < sizeLimit || !fileDePara.getName().toUpperCase().endsWith(".XLSX")){

                                    if (fileDePara.isFile()){ //jjj
                                        logger.logInfo("LENDO OK DEPARA");
                                        atualizaPendencias(versaoPlataforma, diretorioDePara, contabilidade, fileDePara/* = fileDePara.getName() */, empresa, logger);
                                        
                                    }
                                }else{

                                    filename = fileDePara.getAbsolutePath();
                                    filename = filename.replaceAll("\\\\", "/");
                                    FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                    
                                    if (filename.contains("_ID")) {
                                        LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                        // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                        String protocolo_id = cutString(filename.toUpperCase(), "_ID", "_");
                                        
                                        String diretorioProtocolo = "/inout/contabil/"+getNomeContabilidadeWorkflow() + "/" + empresa + "/DePara/";
                                        
                                        atualizaProtocolo("", "NAOLEULINHAS", diretorioProtocolo, protocolo_id, apiWeb, logger);
                                    }
                                }
                            }
                        }
                    } catch (Exception deParaException) {
                        logger.logError("Erro executando DePara " + diretorioDePara, deParaException);
                    }
							

                    if (diretorioArquivo.contains("/APagar") && diretorioArquivo.contains("_#")) {
						logger.logInfo("DIREARC " + diretorioArquivo);
                        File file = new File(diretorioArquivo);

                        // renomeia arquivos com extens?o .XLSX 
                        File []  arquivosCaixaAlta = file.listFiles();
                        if (FileUtil.dirHasFiles(diretorioArquivo)) {

                            for (File fl: arquivosCaixaAlta) {
                            
                                logger.logInfo("LENDO EMPRESA pagar = " + empresa);
                            
                                postStatus("S1", INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")), contabilidade, empresa.toUpperCase(), "PAGAR", INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")));


                                if(fl.length() < sizeLimit) {                    // processar apenas arquivos MENORES que o limite
                                    try {
                                        String arquivoDestino = fl.getAbsolutePath().replaceAll("\\.XLSX","_\\.xlsx").replaceAll("\\.PDF","_\\.pdf").toLowerCase();
                                        if (fl.getAbsolutePath().contains(".XLSX") || fl.getAbsolutePath().contains(".PDF")) {


                                            File fileDestino = new File(arquivoDestino);
                                            FileUtil.copyFolder(fl, fileDestino);
                                            FileUtil.deleteFile(fl);
                                        }
                                    }
                                    catch (Exception xx) {
										logger.logInfo("Quebrou 1 " + xx.getMessage());
									}
                                    
                                    try {
                                        String arquivoDestino = fl.getAbsolutePath().replace("[","").replace("]","").replace("{","").replace("}","").replace("%","");
                                        if (fl.getAbsolutePath().contains("[") || fl.getAbsolutePath().contains("]") || fl.getAbsolutePath().contains("{") || fl.getAbsolutePath().contains("}") || fl.getAbsolutePath().contains("%")) {
                                            File fileDestino = new File(arquivoDestino);
                                            FileUtil.copyFolder(fl, fileDestino);
                                            FileUtil.deleteFile(fl);
                                        }
                                    }
                                    catch (Exception xx) {
										logger.logInfo("Quebrou 2 " + xx.getMessage());
									}
                                }
                                
                                if(fl.getName().toUpperCase().contains("..")){
                                    try {
                                        String arquivoExtensaoCorreta = fl.getAbsolutePath().replaceAll("\\..","\\.");
                                        // if (fl.getAbsolutePath().contains(".XLSX")) {

                                            File fileDestino = new File(arquivoExtensaoCorreta);
                                            FileUtil.copyFolder(fl, fileDestino);
                                            FileUtil.deleteFile(fl);
                                        //}
                                    }
                                    catch (Exception xx) {
										logger.logInfo("Quebrou 3 " + xx.getMessage());
									}
                                }
                            }
                        }


                        // FINAL renomeia arquivos com extens?o .XLSX 
						
						logger.logInfo("ANTES FOR EQUIPE FECHAMENTO");


                        files = file.listFiles();

                        if (FileUtil.dirHasFiles(diretorioArquivo)) {
                            for (File fl: files) {
                                
                                String rodaConversor = props.get(empresa.toUpperCase() + "_EQUIPE_FECHAMENTO");
                                //Conversor
                                if (rodaConversor != null) {
                                    if (rodaConversor.contains(",") && rodaConversor.toUpperCase().contains("CONVERTE") && !fl.getAbsolutePath().toUpperCase().contains(".CSV")
                                        && fl.getAbsolutePath().toUpperCase().contains(".XLSX")) {
                                            
                                        if (fl.getAbsolutePath().toUpperCase().contains(".XLSX") && rodaConversor.contains("XLSX")) {
                                            File arquivoDeploy  = new File("C:/Conversor/Excel/" + "pagar_" + contabilidade + "_" + empresa + "_ancora_" + cutString(fl.getAbsolutePath(), fl.getAbsolutePath().replaceAll("\\\\", "/").lastIndexOf("/")+1));
                                            
                                            try { FileUtil.copyFolder(fl, arquivoDeploy);}
                                            catch (Exception e) {logger.logInfo("ERRO COPIANDO " + e.getMessage());}
                                            
                                            try { 
                                                FileUtil.deleteFile(fl);
                                            } catch (Exception XX) {} 
                                                
                                            continue;
                                        }
                                    }
                                }
                                
                                if (fl.getAbsolutePath().toUpperCase().contains("ROTA.TXT")) {
                                
                                    File arquivoDeploy  = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasPagasEndpointA.script");
                                    File arquivoPortal  = new File(RouteEngine.INOUT_HOME + "/contabil/" + contabilidade + "/arquivos/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasPagasEndpoint.script_APAGAR.txt");
                                    
                                    FileUtil.copyFolder(arquivoDeploy, arquivoPortal);
                                    
                                    try { 
                                            FileUtil.deleteFile(fl);
                                    } catch (Exception XX) {} 
                                    
                                    try { 
                                        FileUtil.deleteFile(fl);
                                    } catch (Exception XX) {} 
                                    
                                    continue;
                                }
                                
                                if (fl.getAbsolutePath().toUpperCase().contains(".SCRIPT")) {
                                
                                    File arquivoDeploy  = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasPagasEndpointA.script");
                                    
                                    FileUtil.copyFolder(fl, arquivoDeploy);

                                    try { 
                                            FileUtil.deleteFile(fl);
                                    } catch (Exception XX) {} 
                                    
                                    
                                    continue;
                                }
                                
                                
                                if((fl.length() >= sizeLimit * 5) || (fl.length() >= sizeLimit && fl.getAbsolutePath().toUpperCase().contains(".XLSX"))){                    // processar apenas arquivos MENORES que o limite
                                    // processar apenas arquivos MENORES que o limite
                                    arquivoGrande = fl.getName();
                                    jSdir = fl.getAbsolutePath();
                                    jSdir = jSdir.replaceAll("\\\\", "/");
                                    jSdir = cutString(jSdir, 0, jSdir.lastIndexOf("/"));
                                    arquivoGrande = "Arquivo-Grande" + arquivoGrande + "_PAGAR";
                                    //jStatus = new JSONObject();
                                    //putStatus(dirName, "", jStatus, logger);
                                    //    putStatus(jSdir, arquivoGrande/* .replaceAll(" ", "-") */ + ".err", jStatus, logger);
                                }
                                
                                /*
                                else {
                                
                                    double sizeBig = (Math.pow(1024,2)); //MiB  

                                    if(fl.length() >= sizeBig) {
                                        String filenameGrande = fl.getAbsolutePath();
                                        filenameGrande = filenameGrande.replaceAll("\\\\", "/");
                                        if (!filenameGrande.endsWith("/Processado")) {
                                            if (!FileUtil.fileExists(diretorio + "/Processado/Grande")) {
                                                FileUtil.mkDir(diretorio + "/Processado/Grande");
                                            }
                                            FileUtil.moveToDir(filenameGrande, diretorio + "/Processado/Grande");
                                        }
                                    }
                                }*/
                                        
                            }

                            for (File fl: files) {
                                if (arquivoGrande.equals("")) {

                                    try {

                                        //renomear arquivo que nao possua extensao para (.txt)
                                        if(fl.isFile() && !fl.getName().contains(".")){
                                            String flStr = fl.getAbsolutePath()+".txt";
                                            File flTemp = new File(flStr);
                                            fl.renameTo(flTemp);
                                        }

                                        if (fl.isFile() && oicContabil.equals("NAO")) {
                                            filename = fl.getAbsolutePath();
                                            filename = filename.replaceAll("\\\\", "/");
                                            FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                            
                                            if (fl.getName().toUpperCase().contains("_ID")){
                        
                                                LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                                // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                String protocolo_id = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                
                                                String diretorioProtocolo = "/inout/contabil/" + contabilidade + "/" + empresa + "/DePara/";
                                                
                                                atualizaProtocolo(oicContabil, "", diretorioProtocolo, protocolo_id, apiWeb, logger);
                                            }
                                            continue;

                                        } else if(fl.isFile() && oicContabil.equals("SIM")){
											
											logger.logInfo("Comecou o processo pagas");

                                            extensaoArquivo = fl.getName().substring(fl.getName().lastIndexOf(".")).toLowerCase();
                                            if(oicEmpresa.equals("NAO")){
                                                //mover para processado arquivo
                                                filename = fl.getAbsolutePath();
                                                filename = filename.replaceAll("\\\\", "/");
                                                FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");

                                            }else if (extensaoSuportada.contains(extensaoArquivo) && !extensaoArquivo.equals(".xls")) {
                                                String nomeRota = contabilidade + "." + empresa.substring(0,empresa.indexOf("_#")) + "_ContasPagas";
                                                
                                                // logger.logInfo("TESTANDODOO " + fl.getName() + " | " + extensaoArquivo.toUpperCase());
                                                //Alterado para esperar uns segundos antes de copiar o arquivo dessa contabilidade por causa do tamanho - In?cio
                                                if (fl.getName().toUpperCase().contains("_ID")) {
                                                    LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                                    // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                    String protocolo_id = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                    
                                                    converteu = converteuPDF(protocolo_id, apiWeb, logger);
                                                    while (!converteu) {
                                                        converteu = converteuPDF(protocolo_id, apiWeb, logger);
                                                    }
                                                }
                                                
                                                try{
                                                
                                                    logger.logInfo("Antes Padrao   " + contabilidade +"_"+ empresa.substring(0,empresa.indexOf("_#")));
                                                
                                                    String tipoProduto = props.get(empresa.toUpperCase().substring(0,empresa.indexOf("_#")).toUpperCase() + "_TIPO_PRODUTO");
                                                    String idRoteiro  = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_ID_ROTEIRO_PAGAR");
                                                    String codRoteiro  = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_ROTEIRO_PAGAR");
                                                    
                                                    // executa rota que atualiza os roteiros das empresas
                                                    // RouteEngine.execRoute("Ottimizza.Oud_AtualizacaoRoteiros");
                                                    atualizaArquivoRoteiro(contabilidade, empresa.substring(0,empresa.indexOf("_#")), logger);
                                                    logger.logInfo("fl.getName() -> " + fl.getName());


                                                    try {
                                                        String rodaPadrao = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_PLANILHA_PADRAO_PAGAR");
                                                        logger.logInfo("PPP " + rodaPadrao + " | " + contabilidade);

                                                        if (rodaPadrao.toUpperCase().trim().equals("TRUE")) {															
                                                            // PartnerConnection connection = Connector.newConnection(config);
															logger.logInfo("EMSS " + idRoteiro + " | " + contabilidade + " | " + empresa.substring(0,empresa.indexOf("_#")) + " | " + dirName + " | " + dirNameW);
                                                            preparaArquivo(idRoteiro, "Contas PAGAS", contabilidade, empresa.substring(0,empresa.indexOf("_#")), dirName, dirNameW, config, logger);

                                                            nomeRota = getNomeContabilidade() + "." + getNomeContabilidade() +  "_ContasPagas";
															logger.logInfo("NRR " + nomeRota);
                                                            double tempoInicio1 = System.currentTimeMillis();
                                                            RouteEngine.execRoute(nomeRota);
                                                            logger.logInfo("Tempo Rota; " + String.format("%.2f", (System.currentTimeMillis() - tempoInicio1) / 1000));
                                                            rodouRota = true;
                                                        }
                                                    }

                                                    catch (Exception xx) {
                                                        logger.logInfo("ERRO AO RODAR ROTEIRO " + xx.getMessage());
                                                    }
                                                    
                                                    logger.logInfo("WFIILI " + tipoProduto);
                                                    
                                                    if (!tipoProduto.contains("ILIMITADA")) {
                                                        preparaArquivoEspecifico(idRoteiro, "Contas PAGAS", contabilidade, empresa.substring(0,empresa.indexOf("_#")), dirName, dirNameW,  logger);

                                                        // Atualia o peoperties eperara para rodar a rota especifica
                                                        // caso o arquvo nao tenha sido rodado na rota padrao

                                                        StringBuilder txt1 = new StringBuilder();    
                                                        String empresaProperties = dirNameW + "empresa.properties";
                                                        FileWriter writer = new FileWriter(empresaProperties);
                                                        txt1.append("NOME_EMPRESA = " + empresa.substring(0,empresa.indexOf("_#")));
                                                        txt1.append("\r\n");
                                                        txt1.append("NOME_CONTABILIDADE = " + contabilidade);
                                                        txt1.append("\r\n");
                                                        txt1.append("MANTEM_ARQUIVO = NAO");
                                                        writer.writeNewFile(txt1.toString());

                                                        empresaProperties = dirName + "empresa.properties";
                                                        writer = new FileWriter(empresaProperties);
                                                        writer.writeNewFile(txt1.toString());  

                                                        File arquivoDeploy  = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasPagasEndpointA.script");
                                                        File eServidor  = new File("C:/inout/docs/processos/producao.txt");
                                                        File arquivoOrigem  = new File(RouteEngine.INOUT_HOME + "/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasPagasEndpointA.script");
                                                        if(eServidor.exists()) {
                                                            FileUtil.copyFolder(arquivoDeploy, arquivoOrigem);
                                                            arquivoOrigem = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasPagasEndpointA.script");
                                                        }

                                                        File arquivoDestino = new File(RouteEngine.INOUT_HOME + "/routes/" + INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) + "/" + INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) + "_ContasPagasEndpointA.script");
                                                        if (empresa.substring(0,empresa.indexOf("_#")).toUpperCase().startsWith("BUSSOLA") && !empresa.substring(0,empresa.indexOf("_#")).toUpperCase().endsWith("BUSSOLA")) arquivoDestino = new File(RouteEngine.INOUT_HOME + "/routes/OTWBussola/LeituraBalanceteEndpointA.script");

                                                        logger.logInfo("ORIGEM  " + arquivoOrigem.getName());
                                                        logger.logInfo("DESTINO " + arquivoDestino.getName());
                                                        FileUtil.copyFolder(arquivoOrigem, arquivoDestino);


                                                        nomeRota = INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) + "." + INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) +  "_ContasPagas";
                                                        if (empresa.substring(0,empresa.indexOf("_#")).toUpperCase().startsWith("BUSSOLA") && !empresa.substring(0,empresa.indexOf("_#")).toUpperCase().endsWith("BUSSOLA")) nomeRota = "OTWBussola.LeituraBalancete";

                                                        logger.logInfo("ROTA   " + nomeRota + "<>" + arquivoOrigem);

                                                        double tempoInicio1 = System.currentTimeMillis();
                                                        RouteEngine.execRoute(nomeRota);
                                                        logger.logInfo("Tempo Rota; " + String.format("%.2f", (System.currentTimeMillis() - tempoInicio1) / 1000));
                                                        rodouRota = true;
                                                        rotasOk = true;
                                                    }
                                                    
                                                    int antesRodar =  files.length;
                                                    boolean naoGerouDepara = true;
                                    
                                    
                                    
                                                    // passos para atualizar o integrador 4.0 
                                                    // PASSO 1: olhar se gerou DEPARA
                                                    // SE ENCONTRAR DEPARA, ATUALIZA STATUS E SEGUE SEM ENVIAR ARQUIVO PRONTO
                                                            
                                                    if (naoGerouDepara && fl.getName().toUpperCase().contains("_ID")) {
                                                        String diretoriArquivos = "/inout/contabil/"+contabilidade + "/" + empresa + "/DePara/";
                                                        File fileArq = new File(diretoriArquivos);
                                                        File [] filesArquivos = fileArq.listFiles();
                                                        try {

                                                            String cnpjEmpresa		 = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_CNPJ_EMPRESA");
                                                            String cnpjContabilidade = props.get("CONTABILIDADE_CNPJ");
                                                            String idSFContabilidade = props.get("CONTABILIDADE_ID");

                                                            if (FileUtil.dirHasFiles(diretoriArquivos)) {
                                                                for (File fileDePara: filesArquivos) {
																	
																	logger.logInfo("FLGTNM " + fileDePara.getName().toUpperCase());

                                                                    if ((fileDePara.getName().toUpperCase().contains(".ERR") || 
                                                                        fileDePara.getName().toUpperCase().contains(".STATUS")) && 
                                                                        fileDePara.getName().toUpperCase().contains("PAGAR")) {
                                                                        //sprint conversorpdf
                                                                        // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                                        String protocolo_id = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                                        String nomeArquivoApagado = cutString(fl.getName().toUpperCase(), "_ID");
                                                                        nomeArquivoApagado = cutString(nomeArquivoApagado, "_", nomeArquivoApagado.lastIndexOf("."));
                                                                        boolean continuaConversor = false;
                                                                        LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                                                        
                                                                        // if (fileDePara.getName().toUpperCase().contains("LEUCONVERSORANTIGO")) {
                                                                            String apagouConversor = apagaArquivoConversor(diretoriArquivos, protocolo_id, nomeArquivoApagado, logger);
                                                                            // JWR 03072023
                                                                            /*if(fileDePara.exists()) {
                                                                                fileDePara.delete();
                                                                                continue;
                                                                            }*/
                                                                        // }
                                                                        //Sprint conversorpdf
                                                                        //Verifica se encontramos algum erro ou status 3 de 4 na pasta do depara, da empresa
                                                                        //Caso encontre, e tenha um id de protocolo, procura algum arquivo na pasta do conversor de pdf
                                                                        //relacionado ao id do protocolo em questao e caso encontre, usaremos esse arquivo para reprocessar a rota.
                                                                        // if (!fileDePara.getName().toUpperCase().contains(".ERR")) continuaConversor = buscaProtocoloConversor(protocolo_id, apiWeb);
                                                                        // if (continuaConversor) continue;
                                                                        atualizaProtocolo("", fileDePara.getName(), diretoriArquivos, protocolo_id, apiWeb, logger);
                                                                        
                                                                        if(fileDePara.exists()) {
                                                                            fileDePara.delete();
                                                                            continue;
                                                                        }
                                                                    }



                                                                    if (!fileDePara.getName().toUpperCase().contains("_ID")) continue;

                                                                    String idLoteFila   = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                                    String idfileDePara = cutString(fileDePara.getName().toUpperCase(), "_ID", "_");

                                                                    if (!idLoteFila.equals(idfileDePara)) continue;


                                                                    LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);

                                                                    // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                                    if(fl.getName().toUpperCase().contains("_ID")) {
                                                                        String apagouConversor = apagaArquivoConversor(diretoriArquivos, cutString(fl.getName().toUpperCase(), "_ID", "_"), "", logger);
                                                                        String atualizaStatus = atualizaStatusProtocoloOic(apiWeb, fl, "1", "Pendencia de preenchimento de contas para este arquivo.",  logger);
                                                                        naoGerouDepara = false;
                                                                    } 

                                                                }

                                                            }
                                                        }
                                                        catch (Exception xx) {}
                                                    }
                                                    
                                                    // PASSO 2: olhar se gerou arquivo pronto e postar no portal.
                                                    if (naoGerouDepara)	{
                                                        String diretoriArquivos = "/inout/contabil/"+contabilidade + "/arquivos/";
                                                        File fileArq = new File(diretoriArquivos);
                                                        File [] filesArquivos = fileArq.listFiles();
                                                        
                                                        
                                                        try {

                                                            String cnpjEmpresa		 = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_CNPJ_EMPRESA");
                                                            String cnpjContabilidade = props.get("CONTABILIDADE_CNPJ");
                                                            String idSFContabilidade = props.get("CONTABILIDADE_ID");

                                                            JSONObject auxObjBucket		= new JSONObject();
                                                            auxObjBucket.put("server",	SERVER_INTEGRADOR_DEV);
                                                            auxObjBucket.put("mapping",	"/api/v1/arquivos_empresas");

                                                            if (FileUtil.dirHasFiles(diretoriArquivos)) {
                                                                for (File fileDePara: filesArquivos) {
                                                                    

                                                                    if (!fileDePara.getName().toUpperCase().contains("_ID")) continue;

                                                                    String idLoteFila   = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                                    String idfileDePara = cutString(fileDePara.getName().toUpperCase(), "_ID", "_");

                                                                    if (!idLoteFila.equals(idfileDePara)) continue;
                                                                    

                                                                    LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);

                                                                    JSONObject jBucket = new JSONObject();
                                                                    jBucket.put("cnpjContabilidade",	cnpjContabilidade);
                                                                    jBucket.put("cnpjEmpresa",			cnpjEmpresa);
                                                                    if (fileDePara.getName().contains("_RECEBER")) {
                                                                        jBucket.put("tipoMovimento", "REC");
                                                                    }
                                                                    else {
                                                                        jBucket.put("tipoMovimento", "PAG");
                                                                    }
                                                                    String nomeArquivo64 = "";


                                                                    jBucket.put("tipoArquivo", "TXT");
                                                                    jBucket.put("nomeArquivo", fileDePara.getName());
                                                                    nomeArquivo64 = fileDePara.getName();

                                                                    String dirRouteNameId= "c:/buckets/oic-arquivo-pronto/"+contabilidade+"/"+DateUtil.dateToString(new Date(), "yyyy/MM/dd")+"/";
                                                                    if (!FileUtil.fileExists(dirRouteNameId)) {
                                                                        FileUtil.mkDir(dirRouteNameId);
                                                                    }

                                                                    File arquivoOrigemId = new File("c:/inout/contabil/"+contabilidade+"/arquivos/" + nomeArquivo64);
                                                                    

                                                                    if (arquivoOrigemId.exists() && ((!fileDePara.getName().toUpperCase().contains("RESUMO_LOTE_") && !fileDePara.getName().toUpperCase().contains("RESUMO_APOS_IMPORTACAO")
                                                                        && !fileDePara.getName().toUpperCase().contains("RESUMO_LOGS_IMPORTACAO")) || fornecedorUnico.contains("EXIBE_RESUMO"))) {
                                                                        File arquivoDeployId  = new File(dirRouteNameId + nomeArquivo64);
                                                                        
                                                                        //JWR Daqui ateh a linha 2123 nao esta deixando o arquivo pronto na pasta arquivos da contabilidade dmassociados empresa treze
                                                                        //estah jogando direto para o enviados. Obs: eh um arquivo .omc
                                                                        
                                                                        FileUtil.copyFolder(arquivoOrigemId, arquivoDeployId);
                                                                        nomeArquivo64 = "https://s1.ottimizza.com.br:55325/storage/"  + Base64.getEncoder().encodeToString((dirRouteNameId + nomeArquivo64).getBytes());
                                                                        jBucket.put("linkArquivo", nomeArquivo64);
                                                                        try {
                                                                            FileUtil.moveToDir("c:/inout/contabil/"+contabilidade+"/arquivos/" + fileDePara.getName(), "c:/inout/contabil/"+contabilidade+"/arquivos/enviados");
                                                                        } catch (Exception xx) {

                                                                        }

                                                                        try {

                                                                            // colocado para nao enviar arquivo de resumo lote
                                                                            // if (!fileDePara.getName().toUpperCase().contains("RESUMO_") || fornecedorUnico.contains("EXIBE_RESUMO")) {
                                                                                String uriIntegrador = String.format("%s%s", auxObjBucket.optString("server"), auxObjBucket.optString("mapping"));
                                                                                String retorno = genericPostId(uriIntegrador, jBucket, apiWeb.token, logger); 

                                                                            // }
                                                                        }
                                                                        catch (Exception xx) {
                                                                            
                                                                            logger.logInfo(" erro genericPostId 2526 "  + xx);


                                                                        }

                                                                        // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                                        if(fl.getName().toUpperCase().contains("_ID")) {
                                                                            String apagouConversor = apagaArquivoConversor(diretoriArquivos, idLoteFila, "", logger);
                                                                            String atualizaStatus = atualizaStatusProtocoloOic(apiWeb, fl, "2", "Arquivo Processado.",  logger);
                                                                        
                                                                        } 
                                                                    }

                                                                }

                                                            }
                                                        }
                                                        catch (Exception xx) {}
                                                    }



                                                    File fileDepoisLista = new File(diretorioArquivo);
                                                    File [] filesDepois = fileDepoisLista.listFiles();
                                                    int depoisRodar =  filesDepois.length;
                                                    
                                                    // caso encontre algum arquivo com o mesmo empresa de antes de rodar a rota
                                                    // move arquivo para pata processado para nao ficar em loop
                                                    for (File fileDePoisComparar: filesDepois) {
                                                        
                                                        if (fileDePoisComparar.getAbsolutePath().equals(fl.getAbsolutePath()) && fl.exists()) {
                                                            String moveFilename = fl.getAbsolutePath();
                                                            moveFilename = moveFilename.replaceAll("\\\\", "/");
                                                            FileUtil.moveToDir(moveFilename, diretorioArquivo + "/Processado");
                                                        }
                                                    }

                                                    if (antesRodar == depoisRodar) {
                                                        String planilhaErro = dirName + empresa + "/DePara" + "/empresa_PAGAR.err";
                                                        FileWriter writerErro = new FileWriter(planilhaErro);
                                                        writerErro.writeNewFile(planilhaErro.toString() + "<<>>" + antesRodar + "<<>>" + depoisRodar);
                                                        if(fl.exists()) {
                                                            //fl.delete();
                                                            filename = fl.getAbsolutePath();
                                                            filename = filename.replaceAll("\\\\", "/");
                                                            FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                                        }
                                                        antesRodar--;
                                                    }
                                                    
                                                    
                                                    if (FileUtil.fileExists(dirName + empresa + "/DePara" + "/02--Etapa 2 de 4--PAGAR.status")) {
                                                        criaAvisoErroLayout( dirName + empresa + "/DePara" + "/02--Etapa 2 de 4--PAGAR.status", logger);

                                                    }


                                                }catch(Exception aa){
                                                    //mover
                                                    filename = fl.getAbsolutePath();
                                                    filename = filename.replaceAll("\\\\", "/");
                                                    FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");

                                                }

                                            } else if(extensaoArquivo.equals(".xls")) {
                                                //mover para processado qualquer arquivo
                                                filename = fl.getAbsolutePath();
                                                filename = filename.replaceAll("\\\\", "/");
                                                FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");

                                            } else {
                                                //mover para processado qualquer arquivo
                                                filename = fl.getAbsolutePath();
                                                filename = filename.replaceAll("\\\\", "/");
                                                FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                            }
                                        }
                                    } catch (Exception eee) {
                                        logger.logError("Erro processando o arquivo " + fl.getAbsolutePath(), eee);
                                    }

                                } else{
                                    filename = fl.getAbsolutePath();
                                    filename = filename.replaceAll("\\\\", "/");
                                    
                                    if (arquivoGrande.toUpperCase().contains("_ID")) {
                                        LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                        // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                        String protocolo_id = cutString(arquivoGrande.toUpperCase(), "_ID", "_");
                                        
                                        String diretorioProtocolo = "/inout/contabil/"+ + "/" + empresa + "/DePara/";
                                        
                                        atualizaProtocolo("", "NAOLEULINHAS", diretorioProtocolo, protocolo_id, apiWeb, logger);
                                    }
                                    
                                    if (!filename.endsWith("/Processado")) FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                }
                            }
                        }

                    }
                    else if (diretorioArquivo.contains("/AReceber") && diretorioArquivo.contains("_#")) {
                        File file = new File(diretorioArquivo);

                        // renomeia arquivos com extens?o .XLSX 
                        File []  arquivosCaixaAlta = file.listFiles();
                        if (FileUtil.dirHasFiles(diretorioArquivo)) {

                            for (File fl: arquivosCaixaAlta) {
                            
                                logger.logInfo("LENDO EMPRESA receber = " + empresa);
                            
                                postStatus("S1", INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")), contabilidade, empresa.toUpperCase(), "RECEBER", INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")));


                                if(fl.length() < sizeLimit) {                    // processar apenas arquivos MENORES que o limite
                                    try {
                                        String arquivoDestino = fl.getAbsolutePath().replaceAll("\\.XLSX","_\\.xlsx").replaceAll("\\.PDF","_\\.pdf").toLowerCase();
                                        if (fl.getAbsolutePath().contains(".XLSX") || fl.getAbsolutePath().contains(".PDF")) {


                                            File fileDestino = new File(arquivoDestino);
                                            FileUtil.copyFolder(fl, fileDestino);
                                            FileUtil.deleteFile(fl);
                                        }
                                    }
                                    catch (Exception xx) {}
                                    
                                    try {
                                        String arquivoDestino = fl.getAbsolutePath().replace("[","").replace("]","").replace("{","").replace("}","").replace("%","");
                                        if (fl.getAbsolutePath().contains("[") || fl.getAbsolutePath().contains("]") || fl.getAbsolutePath().contains("{") || fl.getAbsolutePath().contains("}") || fl.getAbsolutePath().contains("%")) {
                                            File fileDestino = new File(arquivoDestino);
                                            FileUtil.copyFolder(fl, fileDestino);
                                            FileUtil.deleteFile(fl);
                                        }
                                    }
                                    catch (Exception xx) {}
                                }
                                
                                if(fl.getName().toUpperCase().contains("..")){
                                    try {
                                        String arquivoExtensaoCorreta = fl.getAbsolutePath().replaceAll("\\..","\\.");
                                        // if (fl.getAbsolutePath().contains(".XLSX")) {

                                            File fileDestino = new File(arquivoExtensaoCorreta);
                                            FileUtil.copyFolder(fl, fileDestino);
                                            FileUtil.deleteFile(fl);
                                        //}
                                    }
                                    catch (Exception xx) {}
                                }
                            }
                        }


                        // FINAL renomeia arquivos com extens?o .XLSX 


                        files = file.listFiles();

                        if (FileUtil.dirHasFiles(diretorioArquivo)) {
                            for (File fl: files) {
                                
                                String rodaConversor = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_EQUIPE_FECHAMENTO");
                                //Conversor
                                if (rodaConversor != null) {
                                    if (rodaConversor.contains(",") && rodaConversor.toUpperCase().contains("CONVERTE") && !fl.getAbsolutePath().toUpperCase().contains(".CSV")
                                        && fl.getAbsolutePath().toUpperCase().contains(".XLSX")) {
                                            
                                        if (fl.getAbsolutePath().toUpperCase().contains(".XLSX") && rodaConversor.contains("XLSX")) {
                                            File arquivoDeploy  = new File("C:/Conversor/Excel/" + "receber_" + contabilidade + "_" + empresa + "_ancora_" + cutString(fl.getAbsolutePath(), fl.getAbsolutePath().replaceAll("\\\\", "/").lastIndexOf("/")+1));
                                            
                                            try { FileUtil.copyFolder(fl, arquivoDeploy);}
                                            catch (Exception e) {logger.logInfo("ERRO COPIANDO " + e.getMessage());}
                                            
                                            try { 
                                                FileUtil.deleteFile(fl);
                                            } catch (Exception XX) {} 
                                                
                                            continue;
                                        }
                                    }
                                }
                                
                                if (fl.getAbsolutePath().toUpperCase().contains("ROTA.TXT")) {
                                
                                    File arquivoDeploy  = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasRecebidasEndpointA.script");
                                    File arquivoPortal  = new File(RouteEngine.INOUT_HOME + "/contabil/" + contabilidade + "/arquivos/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasRecebidasEndpoint.script_ARECEBER.txt");
                                    
                                    FileUtil.copyFolder(arquivoDeploy, arquivoPortal);
                                    
                                    try { 
                                            FileUtil.deleteFile(fl);
                                    } catch (Exception XX) {} 
                                    
                                    try { 
                                        FileUtil.deleteFile(fl);
                                    } catch (Exception XX) {} 
                                    
                                    continue;
                                }
                                
                                if (fl.getAbsolutePath().toUpperCase().contains(".SCRIPT")) {
                                
                                    File arquivoDeploy  = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasRecebidasEndpointA.script");
                                    
                                    FileUtil.copyFolder(fl, arquivoDeploy);

                                    try { 
                                            FileUtil.deleteFile(fl);
                                    } catch (Exception XX) {} 
                                    
                                    
                                    continue;
                                }
                                
                                
                                if((fl.length() >= sizeLimit * 5) || (fl.length() >= sizeLimit && fl.getAbsolutePath().toUpperCase().contains(".XLSX"))){                    // processar apenas arquivos MENORES que o limite
                                    // processar apenas arquivos MENORES que o limite
                                    arquivoGrande = fl.getName();
                                    jSdir = fl.getAbsolutePath();
                                    jSdir = jSdir.replaceAll("\\\\", "/");
                                    jSdir = cutString(jSdir, 0, jSdir.lastIndexOf("/"));
                                    arquivoGrande = "Arquivo-Grande" + arquivoGrande + "_RECEBER";
                                    //jStatus = new JSONObject();
                                    //putStatus(dirName, "", jStatus, logger);
                                    //    putStatus(jSdir, arquivoGrande/* .replaceAll(" ", "-") */ + ".err", jStatus, logger);
                                }
                                
                                /*
                                else {
                                
                                    double sizeBig = (Math.pow(1024,2)); //MiB  

                                    if(fl.length() >= sizeBig) {
                                        String filenameGrande = fl.getAbsolutePath();
                                        filenameGrande = filenameGrande.replaceAll("\\\\", "/");
                                        if (!filenameGrande.endsWith("/Processado")) {
                                            if (!FileUtil.fileExists(diretorio + "/Processado/Grande")) {
                                                FileUtil.mkDir(diretorio + "/Processado/Grande");
                                            }
                                            FileUtil.moveToDir(filenameGrande, diretorio + "/Processado/Grande");
                                        }
                                    }
                                }*/
                                        
                            }

                            for (File fl: files) {
                                if (arquivoGrande.equals("")) {

                                    try {

                                        //renomear arquivo que nao possua extensao para (.txt)
                                        if(fl.isFile() && !fl.getName().contains(".")){
                                            String flStr = fl.getAbsolutePath()+".txt";
                                            File flTemp = new File(flStr);
                                            fl.renameTo(flTemp);
                                        }

                                        if (fl.isFile() && oicContabil.equals("NAO")) {
                                            //mover para processado arquivo
                                            filename = fl.getAbsolutePath();
                                            filename = filename.replaceAll("\\\\", "/");
                                            FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                            
                                            if (fl.getName().toUpperCase().contains("_ID")){
                        
                                                LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                                // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                String protocolo_id = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                
                                                String diretorioProtocolo = "/inout/contabil/"+getNomeContabilidadeWorkflow() + "/" + empresa + "/DePara/";
                                                
                                                atualizaProtocolo(oicContabil, "", diretorioProtocolo, protocolo_id, apiWeb, logger);
                                            }
                                            continue;

                                        } else if(fl.isFile() && oicContabil.equals("SIM")){

                                            extensaoArquivo = fl.getName().substring(fl.getName().lastIndexOf(".")).toLowerCase();
                                            if(oicEmpresa.equals("NAO")){
                                                //mover para processado arquivo
                                                filename = fl.getAbsolutePath();
                                                filename = filename.replaceAll("\\\\", "/");
                                                FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");

                                            }else if (extensaoSuportada.contains(extensaoArquivo) && !extensaoArquivo.equals(".xls")) {
                                                String nomeRota = contabilidade + "." + empresa.substring(0,empresa.indexOf("_#")) + "_ContasRecebidas";
                                                
                                                // logger.logInfo("TESTANDODOO " + fl.getName() + " | " + extensaoArquivo.toUpperCase());
                                                //Alterado para esperar uns segundos antes de copiar o arquivo dessa contabilidade por causa do tamanho - In?cio
                                                if (fl.getName().toUpperCase().contains("_ID")) {
                                                    LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                                    // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                    String protocolo_id = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                    
                                                    converteu = converteuPDF(protocolo_id, apiWeb, logger);
                                                    while (!converteu) {
                                                        converteu = converteuPDF(protocolo_id, apiWeb, logger);
                                                    }
                                                }
                                                
                                                try{
                                                
                                                    logger.logInfo("Antes Padrao   " + contabilidade +"_"+ empresa.substring(0,empresa.indexOf("_#")));
                                                
                                                    String tipoProduto = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_TIPO_PRODUTO");
                                                    String idRoteiro  = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_ID_ROTEIRO_RECEBER");
                                                    String codRoteiro  = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_ROTEIRO_RECEBER");
                                                    
                                                    // executa rota que atualiza os roteiros das empresas
                                                    // RouteEngine.execRoute("Ottimizza.Oud_AtualizacaoRoteiros");
                                                    atualizaArquivoRoteiro(contabilidade, empresa.substring(0,empresa.indexOf("_#")), logger);
                                                    logger.logInfo("fl.getName() -> " + fl.getName());


                                                    try {
                                                        String rodaPadrao = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_PLANILHA_PADRAO_RECEBER");
                                                        logger.logInfo("PPP " + rodaPadrao + " | " + contabilidade);

                                                        if (rodaPadrao.toUpperCase().trim().equals("TRUE")) {															
                                                            // PartnerConnection connection = Connector.newConnection(config);
                                                            preparaArquivo(idRoteiro, "Contas RECEBIDAS", contabilidade, empresa.substring(0,empresa.indexOf("_#")), dirName, dirNameW, config, logger);

                                                            nomeRota = getNomeContabilidade() + "." + getNomeContabilidade() +  "_ContasRecebidas";
                                                            double tempoInicio1 = System.currentTimeMillis();
                                                            RouteEngine.execRoute(nomeRota);
                                                            logger.logInfo("Tempo Rota; " + String.format("%.2f", (System.currentTimeMillis() - tempoInicio1) / 1000));
                                                            rodouRota = true;
                                                        }
                                                    }

                                                    catch (Exception xx) {
                                                        logger.logInfo("ERRO AO RODAR ROTEIRO " + xx.getMessage());
                                                    }
                                                    
                                                    logger.logInfo("WFIILI " + tipoProduto);
                                                    
                                                    if (!tipoProduto.contains("ILIMITADA")) {
                                                        preparaArquivoEspecifico(idRoteiro, "Contas RECEBER", contabilidade, empresa.substring(0,empresa.indexOf("_#")), dirName, dirNameW,  logger);

                                                        // Atualia o peoperties eperara para rodar a rota especifica
                                                        // caso o arquvo nao tenha sido rodado na rota padrao

                                                        StringBuilder txt1 = new StringBuilder();    
                                                        String empresaProperties = dirNameW + "empresa.properties";
                                                        FileWriter writer = new FileWriter(empresaProperties);
                                                        txt1.append("NOME_EMPRESA = " + empresa.substring(0,empresa.indexOf("_#")));
                                                        txt1.append("\r\n");
                                                        txt1.append("NOME_CONTABILIDADE = " + contabilidade);
                                                        txt1.append("\r\n");
                                                        txt1.append("MANTEM_ARQUIVO = NAO");
                                                        writer.writeNewFile(txt1.toString());

                                                        empresaProperties = dirName + "empresa.properties";
                                                        writer = new FileWriter(empresaProperties);
                                                        writer.writeNewFile(txt1.toString());  

                                                        File arquivoDeploy  = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasRecebidasEndpointA.script");
                                                        File eServidor  = new File("C:/inout/docs/processos/producao.txt");
                                                        File arquivoOrigem  = new File(RouteEngine.INOUT_HOME + "/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasRecebidasEndpointA.script");
                                                        if(eServidor.exists()) {
                                                            FileUtil.copyFolder(arquivoDeploy, arquivoOrigem);
                                                            arquivoOrigem = new File("C:/ottimizza/Dropbox/Deploy/routes/" + contabilidade + "/" + empresa.substring(0,empresa.indexOf("_#")) + "_ContasRecebidasEndpointA.script");
                                                        }

                                                        File arquivoDestino = new File(RouteEngine.INOUT_HOME + "/routes/" + INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) + "/" + INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) + "_ContasRecebidasEndpointA.script");
                                                        if (empresa.substring(0,empresa.indexOf("_#")).toUpperCase().startsWith("BUSSOLA") && !empresa.substring(0,empresa.indexOf("_#")).toUpperCase().endsWith("BUSSOLA")) arquivoDestino = new File(RouteEngine.INOUT_HOME + "/routes/OTWBussola/LeituraBalanceteEndpointA.script");

                                                        logger.logDebug("ORIGEM  " + arquivoOrigem.getName());
                                                        logger.logDebug("DESTINO " + arquivoDestino.getName());
                                                        FileUtil.copyFolder(arquivoOrigem, arquivoDestino);


                                                        nomeRota = INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) + "." + INOUT_ROUTE_ID.substring(0, INOUT_ROUTE_ID.indexOf(".")) +  "_ContasRecebidas";
                                                        if (empresa.substring(0,empresa.indexOf("_#")).toUpperCase().startsWith("BUSSOLA") && !empresa.substring(0,empresa.indexOf("_#")).toUpperCase().endsWith("BUSSOLA")) nomeRota = "OTWBussola.LeituraBalancete";

                                                        logger.logDebug("ROTA   " + nomeRota + "<>" + arquivoOrigem);

                                                        double tempoInicio1 = System.currentTimeMillis();
                                                        RouteEngine.execRoute(nomeRota);
                                                        logger.logDebug("Tempo Rota; " + String.format("%.2f", (System.currentTimeMillis() - tempoInicio1) / 1000));
                                                        rodouRota = true;
                                                        rotasOk = true;
                                                    }
                                                    
                                                    int antesRodar =  files.length;
                                                    boolean naoGerouDepara = true;
                                    
                                    
                                    
                                                    // passos para atualizar o integrador 4.0 
                                                    // PASSO 1: olhar se gerou DEPARA
                                                    // SE ENCONTRAR DEPARA, ATUALIZA STATUS E SEGUE SEM ENVIAR ARQUIVO PRONTO
                                                            
                                                    if (naoGerouDepara && fl.getName().toUpperCase().contains("_ID")) {
                                                        String diretoriArquivos = "/inout/contabil/"+contabilidade + "/" + empresa + "/DePara/";
                                                        File fileArq = new File(diretoriArquivos);
                                                        File [] filesArquivos = fileArq.listFiles();
                                                        try {

                                                            String cnpjEmpresa		 = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_CNPJ_EMPRESA");
                                                            String cnpjContabilidade = props.get("CONTABILIDADE_CNPJ");
                                                            String idSFContabilidade = props.get("CONTABILIDADE_ID");

                                                            if (FileUtil.dirHasFiles(diretoriArquivos)) {
                                                                for (File fileDePara: filesArquivos) {

                                                                    if ((fileDePara.getName().toUpperCase().contains(".ERR") || 
                                                                        fileDePara.getName().toUpperCase().contains(".STATUS")) && 
                                                                        fileDePara.getName().toUpperCase().contains("RECEBER")) {
                                                                        //sprint conversorpdf
                                                                        // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                                        String protocolo_id = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                                        String nomeArquivoApagado = cutString(fl.getName().toUpperCase(), "_ID");
                                                                        nomeArquivoApagado = cutString(nomeArquivoApagado, "_", nomeArquivoApagado.lastIndexOf("."));
                                                                        boolean continuaConversor = false;
                                                                        LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                                                        
                                                                        // if (fileDePara.getName().toUpperCase().contains("LEUCONVERSORANTIGO")) {
                                                                            String apagouConversor = apagaArquivoConversor(diretoriArquivos, protocolo_id, nomeArquivoApagado, logger);
                                                                            // JWR 03072023
                                                                            /*if(fileDePara.exists()) {
                                                                                fileDePara.delete();
                                                                                continue;
                                                                            }*/
                                                                        // }
                                                                        //Sprint conversorpdf
                                                                        //Verifica se encontramos algum erro ou status 3 de 4 na pasta do depara, da empresa
                                                                        //Caso encontre, e tenha um id de protocolo, procura algum arquivo na pasta do conversor de pdf
                                                                        //relacionado ao id do protocolo em questao e caso encontre, usaremos esse arquivo para reprocessar a rota.
                                                                        // if (!fileDePara.getName().toUpperCase().contains(".ERR")) continuaConversor = buscaProtocoloConversor(protocolo_id, apiWeb);
                                                                        // if (continuaConversor) continue;
                                                                        atualizaProtocolo("", fileDePara.getName(), diretoriArquivos, protocolo_id, apiWeb, logger);
                                                                        
                                                                        if(fileDePara.exists()) {
                                                                            fileDePara.delete();
                                                                            continue;
                                                                        }
                                                                    }



                                                                    if (!fileDePara.getName().toUpperCase().contains("_ID")) continue;

                                                                    String idLoteFila   = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                                    String idfileDePara = cutString(fileDePara.getName().toUpperCase(), "_ID", "_");

                                                                    if (!idLoteFila.equals(idfileDePara)) continue;


                                                                    LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);

                                                                    // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                                    if(fl.getName().toUpperCase().contains("_ID")) {
                                                                        String apagouConversor = apagaArquivoConversor(diretoriArquivos, cutString(fl.getName().toUpperCase(), "_ID", "_"), "", logger);
                                                                        String atualizaStatus = atualizaStatusProtocoloOic(apiWeb, fl, "1", "Pendencia de preenchimento de contas para este arquivo.",  logger);
                                                                        naoGerouDepara = false;
                                                                    } 

                                                                }

                                                            }
                                                        }
                                                        catch (Exception xx) {}
                                                    }
                                                    
                                                    // PASSO 2: olhar se gerou arquivo pronto e postar no portal.
                                                    if (naoGerouDepara)	{
                                                        String diretoriArquivos = "/inout/contabil/"+contabilidade + "/arquivos/";
                                                        File fileArq = new File(diretoriArquivos);
                                                        File [] filesArquivos = fileArq.listFiles();
                                                        
                                                        
                                                        try {

                                                            String cnpjEmpresa		 = props.get(empresa.substring(0,empresa.indexOf("_#")).toUpperCase() + "_CNPJ_EMPRESA");
                                                            String cnpjContabilidade = props.get("CONTABILIDADE_CNPJ");
                                                            String idSFContabilidade = props.get("CONTABILIDADE_ID");

                                                            JSONObject auxObjBucket		= new JSONObject();
                                                            auxObjBucket.put("server",	SERVER_INTEGRADOR_DEV);
                                                            auxObjBucket.put("mapping",	"/api/v1/arquivos_empresas");

                                                            if (FileUtil.dirHasFiles(diretoriArquivos)) {
                                                                for (File fileDePara: filesArquivos) {
                                                                    

                                                                    if (!fileDePara.getName().toUpperCase().contains("_ID")) continue;

                                                                    String idLoteFila   = cutString(fl.getName().toUpperCase(), "_ID", "_");
                                                                    String idfileDePara = cutString(fileDePara.getName().toUpperCase(), "_ID", "_");

                                                                    if (!idLoteFila.equals(idfileDePara)) continue;
                                                                    

                                                                    LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);

                                                                    JSONObject jBucket = new JSONObject();
                                                                    jBucket.put("cnpjContabilidade",	cnpjContabilidade);
                                                                    jBucket.put("cnpjEmpresa",			cnpjEmpresa);
                                                                    if (fileDePara.getName().contains("_RECEBER")) {
                                                                        jBucket.put("tipoMovimento", "REC");
                                                                    }
                                                                    else {
                                                                        jBucket.put("tipoMovimento", "PAG");
                                                                    }
                                                                    String nomeArquivo64 = "";


                                                                    jBucket.put("tipoArquivo", "TXT");
                                                                    jBucket.put("nomeArquivo", fileDePara.getName());
                                                                    nomeArquivo64 = fileDePara.getName();

                                                                    String dirRouteNameId= "c:/buckets/oic-arquivo-pronto/"+contabilidade+"/"+DateUtil.dateToString(new Date(), "yyyy/MM/dd")+"/";
                                                                    if (!FileUtil.fileExists(dirRouteNameId)) {
                                                                        FileUtil.mkDir(dirRouteNameId);
                                                                    }

                                                                    File arquivoOrigemId = new File("c:/inout/contabil/"+contabilidade+"/arquivos/" + nomeArquivo64);
                                                                    

                                                                    if (arquivoOrigemId.exists() && ((!fileDePara.getName().toUpperCase().contains("RESUMO_LOTE_") && !fileDePara.getName().toUpperCase().contains("RESUMO_APOS_IMPORTACAO")
                                                                        && !fileDePara.getName().toUpperCase().contains("RESUMO_LOGS_IMPORTACAO")) || fornecedorUnico.contains("EXIBE_RESUMO"))) {
                                                                        File arquivoDeployId  = new File(dirRouteNameId + nomeArquivo64);
                                                                        
                                                                        //JWR Daqui ateh a linha 2123 nao esta deixando o arquivo pronto na pasta arquivos da contabilidade dmassociados empresa treze
                                                                        //estah jogando direto para o enviados. Obs: eh um arquivo .omc
                                                                        
                                                                        FileUtil.copyFolder(arquivoOrigemId, arquivoDeployId);
                                                                        nomeArquivo64 = "https://s1.ottimizza.com.br:55325/storage/"  + Base64.getEncoder().encodeToString((dirRouteNameId + nomeArquivo64).getBytes());
                                                                        jBucket.put("linkArquivo", nomeArquivo64);
                                                                        try {
                                                                            FileUtil.moveToDir("c:/inout/contabil/"+contabilidade+"/arquivos/" + fileDePara.getName(), "c:/inout/contabil/"+contabilidade+"/arquivos/enviados");
                                                                        } catch (Exception xx) {

                                                                        }

                                                                        try {

                                                                            // colocado para nao enviar arquivo de resumo lote
                                                                            // if (!fileDePara.getName().toUpperCase().contains("RESUMO_") || fornecedorUnico.contains("EXIBE_RESUMO")) {
                                                                                String uriIntegrador = String.format("%s%s", auxObjBucket.optString("server"), auxObjBucket.optString("mapping"));
                                                                                String retorno = genericPostId(uriIntegrador, jBucket, apiWeb.token, logger); 

                                                                            // }
                                                                        }
                                                                        catch (Exception xx) {
                                                                            
                                                                            logger.logDebug(" erro genericPostId 2526 "  + xx);


                                                                        }

                                                                        // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                                                        if(fl.getName().toUpperCase().contains("_ID")) {
                                                                            String apagouConversor = apagaArquivoConversor(diretoriArquivos, idLoteFila, "", logger);
                                                                            String atualizaStatus = atualizaStatusProtocoloOic(apiWeb, fl, "2", "Arquivo Processado.",  logger);
                                                                        
                                                                        } 
                                                                    }

                                                                }

                                                            }
                                                        }
                                                        catch (Exception xx) {}
                                                    }



                                                    File fileDepoisLista = new File(diretorioArquivo);
                                                    File [] filesDepois = fileDepoisLista.listFiles();
                                                    int depoisRodar =  filesDepois.length;
                                                    
                                                    // caso encontre algum arquivo com o mesmo empresa de antes de rodar a rota
                                                    // move arquivo para pata processado para nao ficar em loop
                                                    for (File fileDePoisComparar: filesDepois) {
                                                        
                                                        if (fileDePoisComparar.getAbsolutePath().equals(fl.getAbsolutePath()) && fl.exists()) {
                                                            String moveFilename = fl.getAbsolutePath();
                                                            moveFilename = moveFilename.replaceAll("\\\\", "/");
                                                            FileUtil.moveToDir(moveFilename, diretorioArquivo + "/Processado");
                                                        }
                                                    }

                                                    if (antesRodar == depoisRodar) {
                                                        String planilhaErro = dirName + empresa + "/DePara" + "/empresa_RECEBER.err";
                                                        FileWriter writerErro = new FileWriter(planilhaErro);
                                                        writerErro.writeNewFile(planilhaErro.toString() + "<<>>" + antesRodar + "<<>>" + depoisRodar);
                                                        if(fl.exists()) {
                                                            //fl.delete();
                                                            filename = fl.getAbsolutePath();
                                                            filename = filename.replaceAll("\\\\", "/");
                                                            FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                                        }
                                                        antesRodar--;
                                                    }
                                                    
                                                    
                                                    if (FileUtil.fileExists(dirName + empresa + "/DePara" + "/02--Etapa 2 de 4--RECEBER.status")) {
                                                        criaAvisoErroLayout( dirName + empresa + "/DePara" + "/02--Etapa 2 de 4--RECEBER.status", logger);

                                                    }


                                                }catch(Exception aa){
                                                    //mover
                                                    filename = fl.getAbsolutePath();
                                                    filename = filename.replaceAll("\\\\", "/");
                                                    FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");

                                                }

                                            } else if(extensaoArquivo.equals(".xls")) {
                                                 //mover para processado qualquer arquivo
                                                filename = fl.getAbsolutePath();
                                                filename = filename.replaceAll("\\\\", "/");
                                                FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");

                                            } else {
                                                //mover para processado qualquer arquivo
                                                filename = fl.getAbsolutePath();
                                                filename = filename.replaceAll("\\\\", "/");
                                                FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                            }
                                        }
                                    } catch (Exception eee) {
                                        logger.logError("Erro processando o arquivo " + fl.getAbsolutePath(), eee);
                                    }

                                } else {
                                    filename = fl.getAbsolutePath();
                                    filename = filename.replaceAll("\\\\", "/");
                                    
                                    if (arquivoGrande.toUpperCase().contains("_ID")) {
                                        LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                        // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                        String protocolo_id = cutString(arquivoGrande.toUpperCase(), "_ID", "_");
                                        
                                        String diretorioProtocolo = "/inout/contabil/"+getNomeContabilidadeWorkflow() + "/" + empresa + "/DePara/";
                                        
                                        atualizaProtocolo("", "NAOLEULINHAS", diretorioProtocolo, protocolo_id, apiWeb, logger);
                                    }
                                    
                                    if (!filename.endsWith("/Processado")) FileUtil.moveToDir(filename, diretorioArquivo + "/Processado");
                                }
                            }
                        }


                    }
                    else if (diretorioArquivo.contains("/DePara")) {
                        operacao = "DePara";
                        String diretorio = dirName + empresa + "/DePara";
                        
                        // logger.logDebug("DIRETORIO " + diretorio);
                        
                        file2 = new File(diretorio);
                        files = file2.listFiles();
                        try {
                            if (FileUtil.dirHasFiles(diretorio)) {
                                for (File fileDePara: files) {
                                    if (fileDePara.getName().equals("Processado")) continue; //JWR adicionar esse if caso haja erro de access denied no depara
                                    
                                    // logger.logDebug("LENDO EMPRESA depara = " + empresa + " | " + fileDePara.length() + " | " + sizeLimit + " | " + fileDePara.getName());
                                    if (fileDePara.isFile()){
                                        
                                        //participante
                                        if (fileDePara.getName().toUpperCase().contains("PARTICIPANTE") &&
                                            (fileDePara.getName().toUpperCase().endsWith(".CSV") )){
                                            File ImportaParticipante = new File(String.format("%s/contabil/Ottimizza/ImportaParticipante/Participante_%s.txt", RouteEngine.INOUT_HOME, empresa));
                                            // Criar diretorio ottimizza/ImportaPlanoContas se n?o existe.
                                            if (!ImportaParticipante.getParentFile().exists()) ImportaParticipante.getParentFile().mkdirs();

                                            if (!ImportaParticipante.exists()) {
                                                try {
                                                    if (ImportaParticipante.createNewFile()) {
                                                        // String com conteudos do Arquivo '.txt' com os dados para importacao
                                                        // do Plano de Contas da Empresa.
                                                        String txtIPContent = "";
                                                        txtIPContent += String.format("NOME_CONTABILIDADE : %s%n", contabilidade);
                                                        txtIPContent += String.format("NOME_EMPRESA : %s%n", empresa.substring(0, empresa.indexOf("_#")));
                                                        txtIPContent += String.format("CODIGO_EMPRESA : %s%n", empresa.substring(empresa.indexOf("#") + 1));
                                                        // Escrever texto no arquivo
                                                        FileWriter writerDePara = new FileWriter(ImportaParticipante.getAbsolutePath());
                                                        writerDePara.writeNewFile(txtIPContent);
                                                    } else {
                                                        logger.logDebug(String.format("Something went wrong while trying to create file at '%s'...\nMake sure the specified path doesn't already exists!", ImportaParticipante.getAbsolutePath()));
                                                    }
                                                } catch(Exception createFileException) {
                                                    logger.logError(String.format("Error trying to create file '%s'!", ImportaParticipante.getAbsolutePath()), createFileException);
                                                }
                                            } else {
                                                logger.logDebug(String.format("File '%s' not created. \nThe file already exists!", ImportaParticipante.getAbsolutePath()));
                                            }
                                            String rotaImportaPlano = "Ottimizza.ImportaParticipante";
                                            RouteEngine.execRoute(rotaImportaPlano);

                                            // caso encontre algum arquivo com o mesmo empresa de antes de rodar a rota
                                            // move arquivo para pata processado para nao ficar em loop
                                            File fileDepoisLista = new File(diretorio);
                                            File [] filesDepois = fileDepoisLista.listFiles();
                                            for (File fileDePoisComparar: filesDepois) {
                                                if (fileDePoisComparar.getAbsolutePath().equals(fileDePara.getAbsolutePath()) && fileDePara.exists()) {
                                                    String moveFilename = fileDePara.getAbsolutePath();
                                                    moveFilename = moveFilename.replaceAll("\\\\", "/");
                                                    FileUtil.moveToDir(moveFilename, diretorio + "/Processado");
                                                }
                                            }

                                        }

                                        

                                        if(fileDePara.length() < sizeLimit || !fileDePara.getName().toUpperCase().endsWith(".XLSX")){
                                            //DE PARA
                                            //atualizaPendencias(versaoPlataforma, diretorio, contabilidade, fileDePara/* = fileDePara.getName() */, empresa);
                                            //PLANO CONTAS
                                            
                                            // logger.logDebug("PLNCNT " + fileDePara.getName() + " | " + contabilidade);
                                            
                                            if (!fileDePara.getName().toUpperCase().contains("PARTICIPANTE") && 
                                                fileDePara.getName().toUpperCase().contains("PLANO") &&
                                            (((fileDePara.getName().toUpperCase().startsWith("PLANO DE CONTA") || fileDePara.getName().toUpperCase().startsWith("PLANOCONTAS")) && fileDePara.getName().toUpperCase().endsWith(".CSV")) || 
                                                fileDePara.getName().toUpperCase().endsWith(".XLSX") || fileDePara.getName().toUpperCase().endsWith(".LST") || fileDePara.getName().toUpperCase().endsWith(".TXT") || fileDePara.getName().toUpperCase().endsWith(".PDF"))) {                    
                                                File txtImportaPlanoContas = new File(String.format("%s/contabil/Ottimizza/ImportaPlanoContas/PlanoContas_%s.txt", RouteEngine.INOUT_HOME, empresa));


                                                // Criar diretorio ottimizza/ImportaPlanoContas se n?o existe.
                                                if (!txtImportaPlanoContas.getParentFile().exists()) txtImportaPlanoContas.getParentFile().mkdirs();

                                                // QUANDO FOR CSV, joga em pasta /inout/contabil/ottimizza/planocontas para poder importar
                                                // sem dar conflito com os .csv de depara. 
                                                if (fileDePara.getName().toUpperCase().endsWith(".CSV") || fileDePara.getName().toUpperCase().endsWith(".PDF")) {
                                                    filename = fileDePara.getAbsolutePath();
                                                    filename = filename.replaceAll("\\\\", "/");

                                                    if (!FileUtil.fileExists(String.format("%s/contabil/Ottimizza/ImportaPlanoContas/%s", RouteEngine.INOUT_HOME, contabilidade))) {
                                                        FileUtil.mkDir(String.format("%s/contabil/Ottimizza/ImportaPlanoContas/%s", RouteEngine.INOUT_HOME, contabilidade));
                                                    }

                                                    
                                                    FileUtil.moveToDir(filename, String.format("%s/contabil/Ottimizza/ImportaPlanoContas/%s", RouteEngine.INOUT_HOME, contabilidade));

                                                }
                                                if (!txtImportaPlanoContas.exists()) {
                                                    try {
                                                        if (txtImportaPlanoContas.createNewFile()) {
                                                            // String com conteudos do Arquivo '.txt' com os dados para importacao 
                                                            // do Plano de Contas da Empresa.
                                                            String txtIPCContent = "";

                                                            txtIPCContent += String.format("NOME_CONTABILIDADE : %s%n", contabilidade);
                                                            txtIPCContent += String.format("NOME_EMPRESA : %s%n", empresa.substring(0, empresa.indexOf("_#")));
                                                            txtIPCContent += String.format("CODIGO_EMPRESA : %s%n", empresa.substring(empresa.indexOf("#") + 1));

                                                            // Escrever texto no arquivo
                                                            FileWriter writerDePara = new FileWriter(txtImportaPlanoContas.getAbsolutePath());
                                                            writerDePara.writeNewFile(txtIPCContent);
                                                        } else {
                                                            logger.logDebug(String.format("Something went wrong while trying to create file at '%s'...\nMake sure the specified path doesn't already exists!", txtImportaPlanoContas.getAbsolutePath()));
                                                        }   
                                                    } catch(Exception createFileException) {
                                                        logger.logError(String.format("Error trying to create file '%s'!", txtImportaPlanoContas.getAbsolutePath()), createFileException);
                                                    }
                                                } else {
                                                    logger.logDebug(String.format("File '%s' not created. \nThe file already exists!", txtImportaPlanoContas.getAbsolutePath()));
                                                }                                            
                                                String rotaImportaPlano = "Ottimizza.ImportaPlanoContas";
                                                RouteEngine.execRoute(rotaImportaPlano);
                                            
                                                // caso encontre algum arquivo com o mesmo empresa de antes de rodar a rota
                                                // move arquivo para pata processado para nao ficar em loop
                                                File fileDepoisLista = new File(diretorio);
                                                File [] filesDepois = fileDepoisLista.listFiles();
                                                for (File fileDePoisComparar: filesDepois) {
                                                    if (fileDePoisComparar.getAbsolutePath().equals(fileDePara.getAbsolutePath()) && fileDePara.exists()) {
                                                        String moveFilename = fileDePara.getAbsolutePath();
                                                        moveFilename = moveFilename.replaceAll("\\\\", "/");
                                                        FileUtil.moveToDir(moveFilename, diretorio + "/Processado");
                                                    }
                                                }

                                            }
                                        }
                                    }else{
                                        filename = fileDePara.getAbsolutePath();
                                        filename = filename.replaceAll("\\\\", "/");
                                        FileUtil.moveToDir(filename, diretorio + "/Processado");
                                        
                                        if (filename.contains("_ID")) {
                                            LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
                                            // adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
                                            String protocolo_id = cutString(filename.toUpperCase(), "_ID", "_");
                                            
                                            String diretorioProtocolo = "/inout/contabil/"+getNomeContabilidadeWorkflow() + "/" + empresa + "/DePara/";
                                            
                                            atualizaProtocolo("", "NAOLEULINHAS", diretorioProtocolo, protocolo_id, apiWeb, logger);
                                        }
                                    }
                                }
                            }
                        } catch (Exception deParaException) {
                            logger.logError("Erro executando DePara " + diretorio, deParaException);
                        }

                    }
                }

            }
        }

        /*if (objetoFila.has("ID")) {
            deleteFila(objetoFila.optInt("ID"), dbIOContOtt, logger);
        }*/

        if (dbIOContOtt != null) {
            dbIOContOtt.closeConnection();
            dbIOContOtt = null;
        }


    } catch (Exception e) {}

    return records;
}

////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////  METODOS AUXILIARES  ////
////////////////////////////////////////  METODOS AUXILIARES  //////////////////////
//////////////////////  METODOS AUXILIARES  ////////////////////////////////////////
////  METODOS AUXILIARES  //////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////

public void preparaArquivo(String idRoteiro, String tipoIntegracao, String contabilidade, String empresa, String dirName, String dirNameW, ConnectorConfig config, InoutLogger logger) {

	try {
		StringBuilder txt1 = new StringBuilder();    
		String empresaProperties = dirName + "empresa.properties";
		FileWriter writer = new FileWriter(empresaProperties);
		txt1.append("NOME_EMPRESA = " + empresa);
		txt1.append("\r\n");
		txt1.append("NOME_CONTABILIDADE = " + contabilidade);
		txt1.append("\r\n");
		txt1.append("MANTEM_ARQUIVO = SIM");
		logger.logDebug("tt " + txt1.toString());
		
		writer.writeNewFile(txt1.toString());

		empresaProperties = dirNameW + "empresa.properties";
		writer = new FileWriter(empresaProperties);
		writer.writeNewFile(txt1.toString());
		
		logger.logDebug("preparaArquivo padrao w - 3 " + contabilidade + "/" + empresa);

	
		StringBuilder codigoNovo    = new StringBuilder();
		StringBuilder codigoRoteiro = new StringBuilder();
		
		FileReader reader = new FileReader("c:/ottimizza/dropbox/deploy/routes/ottimizza/TemplateOficialAtualEndpointA.script");
		try {
			reader.openFile();
			String line = "";
			while(reader.hasNextLine()) {
				// Le a proxima linha do arquivo
				line = reader.nextLine();
				// Processa a linha
				// ....
				
				codigoNovo.append(line);
				if (line.contains("NAO ALTERAR DAQUI ATE O FINAL")) break;				
			}
		} catch (IOException ioe) {
			logger.logError(ioe);
		} finally {
			reader.closeFile();
		}
		
		String tipoRoteiro = "_ContasPagasRoteiroPadrao.script";
		if (tipoIntegracao.toUpperCase().contains("RECE")) tipoRoteiro = "_ContasRecebidasRoteiroPadrao.script";
		
		logger.logDebug("AQQ " + "c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
		
 			
		try {
			File fileRoteiro = new File("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
  

			//logger.logDebug("fileRoteiro w - 3 " + contabilidade + "/" + empresa);

		    //if (fileRoteiro.exists() && tipoRoteiro.contains("TESTE XAVIER")) {
			if (fileRoteiro.exists() &&
			    !(/*contabilidade.toUpperCase().contains("MICALI") ||*/ contabilidade.toUpperCase().contains("CONCEITOCONTABILIDADE"))) {
				
  				
				FileReader readerRoteiro = new FileReader("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
				try {
					readerRoteiro.openFile();
					String lineRoteiro = "";
					while(readerRoteiro.hasNextLine()) {
						// Le a proxima linha do arquivo
						lineRoteiro = readerRoteiro.nextLine();
						// Processa a linha
						// ....
						
						codigoRoteiro.append(lineRoteiro);
 					}
				} catch (IOException ioe) {
					logger.logError(ioe);
				} finally {
					readerRoteiro.closeFile();
				}
			}
			else {
 
 				PartnerConnection connection = Connector.newConnection(config);  
				codigoRoteiro.append(prepareScript(idRoteiro, "OTTPADRAO" + empresa, "", contabilidade, tipoIntegracao, connection, logger));
				logger.logDebug("WF3 - login salesforce 3350" + contabilidade + "--" + empresa);
				
  				
			}
		} catch (Exception xx) {logger.logDebug("erro w3 " + xx);}
		
 
		if (!codigoRoteiro.toString().equals("")) {
		
			empresaProperties = "";
 			
			if (tipoIntegracao.toUpperCase().contains("PAGA"))  empresaProperties = RouteEngine.INOUT_HOME + "/routes/" + getNomeContabilidade() + "/" + getNomeContabilidade() + "_ContasPagasEndpointA.script";
			if (tipoIntegracao.toUpperCase().contains("RECE"))  empresaProperties = RouteEngine.INOUT_HOME + "/routes/" + getNomeContabilidade() + "/" + getNomeContabilidade() + "_ContasRecebidasEndpointA.script";
			writer = new FileWriter(empresaProperties);
			writer.writeNewFile(codigoNovo.toString() + codigoRoteiro.toString());			
			
			writer = new FileWriter("c:/inout/tmp/"+contabilidade+"_copia.txt");
			writer.writeNewFile(codigoNovo.toString() + codigoRoteiro.toString());
			
		    writer = new FileWriter("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
			writer.writeNewFile(codigoRoteiro.toString());			

		}		
 	}
	catch (Exception xx) {}
	return;
}


public void preparaArquivoEspecifico(String idRoteiro, String tipoIntegracao, String contabilidade, String empresa, String dirName, String dirNameW, InoutLogger logger) {

	try {
		StringBuilder txt1 = new StringBuilder();    
		String empresaProperties = dirName + "empresa.properties";
		FileWriter writer = new FileWriter(empresaProperties);
		txt1.append("NOME_EMPRESA = " + empresa);
		txt1.append("\r\n");
		txt1.append("NOME_CONTABILIDADE = " + contabilidade);
		txt1.append("\r\n");
		txt1.append("MANTEM_ARQUIVO = SIM");
		writer.writeNewFile(txt1.toString());

		empresaProperties = dirNameW + "empresa.properties";
		writer = new FileWriter(empresaProperties);
		writer.writeNewFile(txt1.toString());
		
 		logger.logDebug("preparaArquivoEspecifico w3 " + contabilidade + "/" + empresa);

	
		StringBuilder codigoNovo    = new StringBuilder();
		StringBuilder codigoRoteiro = new StringBuilder();
		String tipoRoteiro = "_ContasPagasRoteiro.script";
		String tipoRota = "_ContasPagasEndpointA.script";
		if (tipoIntegracao.toUpperCase().contains("RECE")) {
			tipoRoteiro = "_ContasRecebidasRoteiro.script";
			tipoRota = "_ContasRecebidasEndpointA.script";
		}
		
		try {
			
			
			FileReader reader = new FileReader("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRota);
			try {
				reader.openFile();
				String line = "";
				while(reader.hasNextLine()) {
					// Le a proxima linha do arquivo
					line = reader.nextLine();
					// Processa a linha
					// ....
					
					codigoNovo.append(line);
					if (line.contains("NAO ALTERAR DAQUI ATE O FINAL")) break;				
				}
			} catch (IOException ioe) {
				logger.logError(ioe);
			} finally {
				reader.closeFile();
			}
 
 			File fileRoteiro = new File("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);

			if (fileRoteiro.exists() &&
			    !(/*contabilidade.toUpperCase().contains("MICALI") ||*/ contabilidade.toUpperCase().contains("CONCEITOCONTABILIDADE"))) {
 				
				FileReader readerRoteiro = new FileReader("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
				try {
					readerRoteiro.openFile();
					String lineRoteiro = "";
					while(readerRoteiro.hasNextLine()) {
						// Le a proxima linha do arquivo
						lineRoteiro = readerRoteiro.nextLine();
						// Processa a linha
						// ....
						
						codigoRoteiro.append(lineRoteiro);
 					}
				} catch (IOException ioe) {
					logger.logError(ioe);
				} finally {
					readerRoteiro.closeFile();
				}
			}
			else {
				ConnectorConfig config = new ConnectorConfig();
				config.setUsername("fabrica@ottimizza.com.br");
				config.setPassword("ottimizza@123HU4ssqt1HCiLyCzj6QStgteM2");
				config.setTraceMessage(false);
				 
				//config.setUsername("adm@ottimizza.com.br");
				//config.setPassword("oic@3333222YXZRHYLH8cxrchPu0rjyGH1j8");
				//config.setTraceMessage(true);
				
				PartnerConnection connection = Connector.newConnection(config);  
				
				// retirado o ottpadrao do preparascript (especifico pois em integracoes antigas
				// estava dando erro de compilacao pois exportavamos o metodo mas ha dentro da rota o mesmo metodo
				codigoRoteiro.append(prepareScript(idRoteiro, "" + empresa, "", contabilidade, tipoIntegracao, connection, logger));
				
				logger.logDebug("WF3 - login salesforce 3464" + contabilidade + "--" + empresa);
				
			}
		} catch (Exception xx) {logger.logDebug("XX " + xx);}
		
 
		if (!codigoRoteiro.toString().equals("")) {
		
			empresaProperties = "";
 			
			if (tipoIntegracao.toUpperCase().contains("PAGA"))  empresaProperties = "c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + "_ContasPagasEndpointA.script";
			if (tipoIntegracao.toUpperCase().contains("RECE"))  empresaProperties = "c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + "_ContasRecebidasEndpointA.script";
			writer = new FileWriter(empresaProperties);
			writer.writeNewFile(codigoNovo.toString() + codigoRoteiro.toString());			
			
			writer = new FileWriter("c:/inout/tmp/"+contabilidade+"_copia_especifico.txt");
			writer.writeNewFile(codigoNovo.toString() + codigoRoteiro.toString());
			
			writer = new FileWriter("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
			writer.writeNewFile(codigoRoteiro.toString());	
		}		
 	}
	catch (Exception xx) {}
	return;
}


public void criaAvisoErroLayout (String arquivo,InoutLogger logger) {

    try {


        FileUtil.deleteFile(arquivo);
        arquivo = arquivo.replaceAll("\\.status",".err");


        FileWriter writerRazao = new FileWriter(arquivo);

        StringBuilder sb1 = new StringBuilder();       
        
        sb1.append("<div class=\"er-content\">").append("\r\n");
        sb1.append("<div class=\"er-message\">").append("\r\n");


        sb1.append("<p>Esta planilha nao pode ser processada pela Ottimizza. Alguns motivos:</p>").append("\r\n");
        sb1.append("</div>").append("\r\n");
        sb1.append("<ul class=\"ul-tips\">").append("\r\n");
		
		StringBuilder mens = new StringBuilder();
		String dirName = cutString(arquivo, 0, "DePara") + "/DePara/Processado";
		logger.logDebug("LENDO workflow script  = " + dirName);
		
		FilesLoader fileLoader2 = new FilesLoader(dirName, "TIPOPLANILHA.txt", dirName+"/lido", true, logger);
		fileLoader2.loadFiles();
		for (MemoryFile memFile: fileLoader2.getMemFiles()) {
			while (memFile.hasNextLine()) {
				try {
					mens.append(memFile.nextLine()).append("    ");
				} catch (Exception xx) {}
			}
		}
							
		if (!mens.toString().equals("")) {
	        sb1.append("<li class=\"it-tip\">").append("\r\n");
			sb1.append("<span><cont color=\red\">").append(mens.toString()).append("</font></span>").append("\r\n");
			sb1.append("</li>").append("\r\n");
		}
        sb1.append("<li class=\"it-tip\">").append("\r\n");
        sb1.append("<span><cont color=\red\">Em 95% dos casos isto ocorre porque o layout do arquivo postado difere do arquivo esperado pela integracao.</font></span>").append("\r\n");
        sb1.append("</li>").append("\r\n");

        sb1.append("<li class=\"it-tip\">").append("\r\n");
        sb1.append("<span><cont color=\red\">Verifique tambem se a planilha esta protegida ou com links a outras planilhas</font></span>").append("\r\n");
        sb1.append("</li>").append("\r\n");
 


        sb1.append("<li class=\"it-tip\">").append("\r\n");
        sb1.append("<span>Verifique se a planilha enviada possui formulas para valores, datas, etc.</span>").append("\r\n");
        sb1.append("</li>").append("\r\n");
        sb1.append("</ul>").append("\r\n");
        sb1.append("<div class=\"er-obs\">").append("\r\n");
        sb1.append("<h6>Caso nao encontre problema na planilha processada, entre em contato com o <a href=\"https://suporte.ottimizza.com.br/\">Suporte Ottimizza</a> </h6>").append("\r\n");
        sb1.append("</div>").append("\r\n");
        sb1.append("</div>").append("\r\n");
        sb1.append("</body>").append("\r\n");

		// if (!arquivo.equals("")) {
			//adiciona o campo ProtocoloID para avisar o OUD que o arquivo foi processado.
			// if(arquivo.toUpperCase().contains("_ID")) {
				// String protocolo_id = cutString(arquivo.toUpperCase(), "_ID", "_");
				 
				//roda requisicao para atualizar o satus do protocolo
				// JSONObject bodyProtocolo = new JSONObject();
				
				// bodyProtocolo.put("status", "3");	
				// bodyProtocolo.put("mensagem", "Erro ao ler planilha. Em 95% dos casos isto ocorre porque o layout do arquivo postado difere do arquivo esperado pela integracao. (Codigo erro 2)");
				
				// LancamentosApi apiWeb = new LancamentosApi(USER_OAUTH, PWD_OAUTH, SERVER_OAUTH, logger);
				// String atualizaStatus = apiWeb.atualizaStatusProtocolo("https://integrador-contabil.herokuapp.com", protocolo_id, bodyProtocolo);
			// }
		// }


        writerRazao.writeNewFile(sb1.toString());
    }
    catch (Exception xx) {} 

}



/*
public void  atualizaArquivoRoteiro(String contabilidade, String empresa, InoutLogger logger) throws Exception {
	
	
    SysProperties props  = SysProperties.getInstance();
    SysProperties props2 = SysProperties.getInstance(); 
	 // Carrega as propriedades
    props.load("contabil/" + contabilidade + "/contabil.properties");
    
	String cnpjEmpresa = props.get(empresa.toUpperCase() + "_CNPJ_EMPRESA");
	logger.logDebug("Antes Atualizando Roteiro - " + cnpjEmpresa);


	String arquivoRoteiro  = RouteEngine.INOUT_HOME +  "/contabil/ottimizza/atualizaRoteiros/atualizaRoteiros_"+cnpjEmpresa+"_wf3.txt";
	FileWriter writerWorkflow = new FileWriter(arquivoRoteiro);
 	writerWorkflow.writeNewFile(cnpjEmpresa);
	
	//RouteEngine.execRoute("Ottimizza.Oud_AtualizacaoRoteiros");
	RouteEngine.execRoute("Ottimizza.AtualizaRoteiros40");
	
	logger.logDebug("Atualizando arquivo Roteiro 40 - " + cnpjEmpresa);
	
																		
	// aguarda 5 segundo para dar tempo das regras estarem salvas no salesforce.
	// Thread.sleep(5000);

	
 	
}*/

//-------------------------------------------------------------------------------------
// Manda informacoes para o servidor status
// Vitor 16/05/2022
//-------------------------------------------------------------------------------------


public void postStatus(String servidor, String workflow, String contabilidade, String empresa, String tipo, String id) {
    String url = "https://api-status-server.herokuapp.com/status";


    try {


        JSONObject body = new JSONObject();

        body.put("servidor", servidor);
        body.put("workflow", workflow);
        body.put("contabilidade", contabilidade);
        body.put("empresa", empresa);
        body.put("tipo", tipo);
        body.put("id", servidor + id);

        java.net.URL serviceURL = new java.net.URL(url);

        // Opens java.net.URL as a POST Request
        java.net.HttpURLConnection connection = (java.net.HttpURLConnection) serviceURL.openConnection();
        connection.setDoOutput(true); // indicates a post
        connection.setRequestMethod("POST");
        connection.setRequestProperty("Accept", "application/json");
        connection.setRequestProperty("Content-Type", "application/json");

        try {
            java.io.OutputStream os = connection.getOutputStream();
            os.write(body.toString().getBytes());
            os.flush();
            os.close();
        } catch (Exception ex1) {
            logger.logError("Erro tentando enviar informa??es para o status server -> " + ex1);
        } 

        try {
            java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.InputStreamReader(connection.getInputStream(), "UTF-8"));
            String line;
            StringBuilder responseRaw = new StringBuilder();
            while ((line = reader.readLine()) != null) {
                responseRaw.append(line);
            }
            reader.close();
			
			//logger.logDebug("RESPONSE " + responseRaw.toString());
			//logger.logDebug("BODY     " + body.toString());
			
        } catch (Exception ex2) {
            logger.logError("Segundo Catch " + ex2);
        } 

    } catch (Exception ex2) {
        logger.logError("Segundo Catch " + ex2);
    }

}


// xavier




public String atualizaStatusProtocoloOic(LancamentosApi apiWeb, File fl,  String statusProtocolo, String mensagem, InoutLogger logger) throws Exception {

    try {
		 String protocolo_id = cutString(fl.getName().toUpperCase(), fl.getName().toUpperCase().lastIndexOf("_ID")+3, "_");
		 if (fl.getName().toUpperCase().contains("OUD_ID"))  protocolo_id = cutString(fl.getName().toUpperCase(), "OUD_ID", "_");
		 if (fl.getName().toUpperCase().contains("OUD__ID")) protocolo_id = cutString(fl.getName().toUpperCase(), "OUD__ID", "_");
		// roda requisicao para atualizar o satus do protocolo
		JSONObject bodyProtocolo = new JSONObject();
		bodyProtocolo.put("status", statusProtocolo);	
		bodyProtocolo.put("mensagem", mensagem);
		String atualizaStatus = apiWeb.atualizaStatusProtocolo("https://integrador-contabil.herokuapp.com", protocolo_id, bodyProtocolo);
		
		//logger.logDebug("Status WF3 " + protocolo_id + " <<>> " + bodyProtocolo.toString());
		
	return atualizaStatus;
	} catch (Exception xx) {
		logger.logDebug(" Erro ao Atualizar Status " + xx);
		return "";
	}
 
}


public String genericPostId(String uri, JSONObject bodyObj, String token, InoutLogger logger) throws Exception {

    try {
        StringBuilder responseRaw = new StringBuilder();
        java.net.URL serviceURL = new java.net.URL(uri);

        // Opensjava.net.URL as a POST Request
        java.net.HttpURLConnection connection = (java.net.HttpURLConnection) serviceURL.openConnection();
        connection.setDoOutput(true); // indicates a post
        connection.setRequestMethod("POST");

        // Default Headers.
        connection.setRequestProperty("Accept", "application/json");
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setRequestProperty("Authorization", "Bearer " + token); // header for authorization

        // Writes the Request Body...
        try {
            java.io.OutputStream os = connection.getOutputStream();
            os.write(bodyObj.toString().getBytes());
            os.flush();
            os.close();
        } catch (Exception ex1) {
            logger.logError("Primeiro Catch " + ex1);
        } 

        // Writes the Response Body...
        try {
            java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.InputStreamReader(connection.getInputStream(), "UTF-8"));
            String line;
            while ((line = reader.readLine()) != null) {
                responseRaw.append(line);
            }
            reader.close();
        } catch (Exception ex2) {
            logger.logError("Segundo Catch " + ex2);
        } 

        // checks if it is a valid json
        if (responseRaw.toString().startsWith("{") && responseRaw.toString().endsWith("}")) {
            JSONObject response = new JSONObject(responseRaw.toString());

            // Todo
            return response.toString();
        } 
        else {
            throw new Exception (responseRaw.toString());
        }

    } catch (Exception ex0) { 
        throw ex0;
    }
}


public void atualizaProtocolo(String liberaOic, String tipoErro, String diretoriArquivos, String protocolo_id, LancamentosApi apiWeb, InoutLogger logger) throws Exception {
	
	JSONObject bodyProtocolo = new JSONObject().put("status", "3");
	
	if (tipoErro.contains("NAOLEULINHAS")) {
		bodyProtocolo.put("mensagem", "Ooops. Arquivo com grande volume. Entre em contato com a equipe de atendimento para maiores orienta??es.");
	}
	else if (tipoErro.contains("NAOLEUIGNORAR")) {
		bodyProtocolo.put("mensagem", "Ooops. N?o conseguimos ler nenhum movimento de pagamento/recebimento nesse arquivo. Verifique as regras criadas de IGNORAR.");
	}
	else if (tipoErro.contains("NAOLEUFILTRO")) {
		bodyProtocolo.put("mensagem", "Ooops. N?o conseguimos ler nenhum movimento pois n?o h? lan?amento no per?odo informado. Verifique a data das movimenta??es dentro do arquivo.");
	}
	else if (tipoErro.contains("NAOLEUMOVIMENTO")) {
		bodyProtocolo.put("mensagem", "Ooops. O layout do arquivo enviado n?o est? de acordo. Por gentileza, verifique o mesmo. Caso seja um relat?rio de extrato ou cart?o, verifique os modelos dispon?veis em nosso portal e certifique-se de ter selecionado a leitura do mesmo.");
	}
	else if (liberaOic.equals("NAO")) {
		bodyProtocolo.put("mensagem", "Ooops. Devido a alguma quest?o administrativa, seu cadastro n?o est? ativo no sistema. Contate o setor financeiro ( e-mail financeiro01@ottimizza.com.br ou 47 9636-4529)");
	}
	else {
		bodyProtocolo.put("mensagem", "Ooops. N?o conseguimos ler nenhum movimento nesse arquivo. Entre em contato com a equipe de atendimento para maiores orienta??es.");
	}
	
	putStatus(diretoriArquivos, "", new JSONObject(), logger);
	
	String atualizaStatus = apiWeb.atualizaStatusProtocolo("https://integrador-contabil.herokuapp.com", protocolo_id, bodyProtocolo);
}

public boolean buscaProtocoloConversor(String protocolo_id, LancamentosApi apiWeb) throws Exception {
	//Conversor
	String diretorio = "C:/Conversor/Pdf";
	File file2 = new File(diretorio);
	
	File [] files = file2.listFiles();
	
	if (FileUtil.dirHasFiles(diretorio)) {
		
		boolean notificouProtocolo = false;	
		
		for (File fl: files) {
			if (fl.getAbsolutePath().contains(protocolo_id)) {
				if ((fl.getAbsolutePath().contains("pagar") || fl.getAbsolutePath().contains("receber")) && fl.getAbsolutePath().contains("#") && fl.getAbsolutePath().toUpperCase().contains(".CSV") && fl.getAbsolutePath().contains("_ancora_") && fl.length() > 0){
					String diretorioArquivoCsv = "C:/inout/contabil/";
					String testeCsv = "";									
					String contabilidadeCsv = "";
					String empresaCsv = "";
					
					if (fl.getAbsolutePath().contains("pagar_")) {
						try {											
							testeCsv = cutString(fl.getAbsolutePath(), "pagar_");
							contabilidadeCsv = testeCsv.substring(0, testeCsv.indexOf("_"));
							empresaCsv = testeCsv.substring(testeCsv.indexOf("_")+1);
							empresaCsv = empresaCsv.substring(0, empresaCsv.indexOf("_ancora_"));
							diretorioArquivoCsv += contabilidadeCsv + "/" + empresaCsv + "/APagar";
						} catch (Exception e) {
							logger.logDebug("ERRO AO CORTAR ARQUIVO " + e.getMessage());
						}
					}
					else if (fl.getAbsolutePath().contains("receber_")) {
						try {											
							testeCsv = cutString(fl.getAbsolutePath(), "receber_");
							contabilidadeCsv = testeCsv.substring(0, testeCsv.indexOf("_"));
							empresaCsv = testeCsv.substring(testeCsv.indexOf("_")+1);
							empresaCsv = empresaCsv.substring(0, empresaCsv.indexOf("_ancora_"));
							diretorioArquivoCsv += contabilidadeCsv + "/" + empresaCsv + "/AReceber";
						} catch (Exception e) {
							logger.logDebug("ERRO AO CORTAR ARQUIVO " + e.getMessage());
						}
					}
					String arquivoDeployStr = "";
					try {							

					// mantivemos o ancora no empresa do arquivo para saber que foi convertido e usado nos extratos
						arquivoDeployStr = fl.getAbsolutePath().substring(fl.getAbsolutePath().indexOf("_ancora_"));
					} catch (Exception e) {
						logger.logDebug("NAOCRIOURODACONVERSOR " + e.getMessage());
					}
					if (!arquivoDeployStr.equals("")) {
						File arquivoDeploy  = new File(diretorioArquivoCsv + "/" + arquivoDeployStr);
						FileUtil.copyFolder(fl, arquivoDeploy);
						
						try { 
							FileUtil.deleteFile(fl);
						} catch (Exception XX) {}
					}
					if (!notificouProtocolo) {
						notificouProtocolo = true;
						// String atualizaStatus = atualizaStatusProtocoloOic(apiWeb, fl, "0", "Estamos convertendo os PDFs.",  logger);
					}
					continue;
				}
			}
		}
		if (notificouProtocolo) return true;
	}
	return false;
}

public boolean converteuPDF(String protocolo_id, LancamentosApi apiWeb, InoutLogger logger) throws Exception {
	//Conversor
	// String diretorio = "C:/Conversor/Pdf";
	String diretorio = "C:/Conversor/Pdf";
	File file2 = new File(diretorio);
	
	File [] files = file2.listFiles();
	// logger.logDebug("ACHANDO");
	
	if (FileUtil.dirHasFiles(diretorio)) {
		
		boolean notificouProtocolo = false;	
		
		for (File fl: files) {
			if (fl.getAbsolutePath().contains(protocolo_id)) {
				// logger.logDebug("ACHOUID " + fl.getAbsolutePath());
				if ((fl.getAbsolutePath().contains("pagar") || fl.getAbsolutePath().contains("receber")) && fl.getAbsolutePath().contains("#") && fl.getAbsolutePath().toUpperCase().contains(".CSV") && fl.getAbsolutePath().contains("_ancora_") /*&& fl.length() > 0*/) {
					// logger.logDebug("ACHOUCSV " + fl.getAbsolutePath());
					return true;
				}
				//2310-020397 adicionado o if abaixo para nao travar quando houver .pdferr
				if ((fl.getAbsolutePath().contains("pagar") || fl.getAbsolutePath().contains("receber")) && fl.getAbsolutePath().contains("#") && fl.getAbsolutePath().toUpperCase().contains(".PDFERR") && fl.getAbsolutePath().contains("_ancora_") /*&& fl.length() > 0*/) {
					// logger.logDebug("ACHOUCSV " + fl.getAbsolutePath());
					try {
						FileUtil.deleteFile(fl);
					} catch (Exception XX) {
						logger.logDebug("PROBLEMA APAGANDO PASTA CONVERSOR " + XX.getMessage());
					}
					return true;
				}
				return false;
			}
		}
	}
	return true;
}

public String apagaArquivoConversor(String diretoriArquivos, String protocolo_id, String nomeArquivo, InoutLogger logger) throws Exception {
	
	String diretorio = "C:/Conversor/Pdf";
	File file2 = new File(diretorio);
	
	File [] files = file2.listFiles();
	
	logger.logDebug("AAC " + protocolo_id + " | " + nomeArquivo);
	
	if (FileUtil.dirHasFiles(diretorio)) {
		for (File fl: files) {
			// logger.logDebug("AAPP " + fl.getAbsolutePath().toUpperCase());
			if (fl.getAbsolutePath().contains("_id"+protocolo_id)/* && fl.getAbsolutePath().toUpperCase().contains(nomeArquivo)*/) {
				if ((fl.getAbsolutePath().contains("pagar") || fl.getAbsolutePath().contains("receber")) && fl.getAbsolutePath().contains("#") && /*fl.getAbsolutePath().toUpperCase().contains(".CSV") &&*/ fl.getAbsolutePath().contains("_ancora_")){
					logger.logDebug("APAGOU " + fl.getAbsolutePath());
					try {
						FileUtil.deleteFile(fl);
					} catch (Exception XX) {
						logger.logDebug("PROBLEMA APAGANDO PASTA CONVERSOR " + XX.getMessage());
					}
					putStatus(diretoriArquivos, "", new JSONObject(), logger);
					// return "APAGOU";
				}
			}
		}
	}

	return "";
	
}

public synchronized JSONObject buscaDiretorioArquivoProcessado(DataBase db, InoutLogger logger) {
	JSONObject jdiretorioArquivo = new JSONObject();
		
	try {
		jdiretorioArquivo = db.sql("SELECT DIRETORIO, ID FROM IO_FILA ORDER BY ID ASC")
								.setFields("DIRETORIO, ID")
								.debug(logger)
								.queryUnique();
	} catch (Exception e) {
		logger.logInfo("ERRO SELECT NA FILA " + e.getMessage());
	}
	
	if (!jdiretorioArquivo.has("DIRETORIO")) return new JSONObject;
	
	String uniqueID = java.util.UUID.randomUUID().toString();

	// File renamedFile = new File(fileToProcess.getParent(), uniqueID + "_" + fileToProcess.getName());
	// File renamedFile = new File("C:/inout/contabil/Micalicontabil/Gabrielavec_#20/APagar" + uniqueID); teste
	File renamedFile = new File(jdiretorioArquivo.optString("DIRETORIO") + uniqueID);



	File file2 = new File(jdiretorioArquivo.optString("DIRETORIO"));
	
	try {
		// Files.move(renamedFile.toPath(), processedDir.resolve(renamedFile.getName()), StandardCopyOption.REPLACE_EXISTING);
		// File file2 = new File("C:/inout/contabil/Micalicontabil/Gabrielavec_#20/APagar"); //simulando o diretorio que vem do banco de dados
		// java.nio.file.Path path = java.nio.file.Paths.get("C:/inout/contabil/Micalicontabil/Gabrielavec_#20/APagar");

		// Gera um identificador único para o processo ou thread atual

		
		try {

			// Tenta renomear o arquivo automicamente

			if (file2.renameTo(renamedFile)) {

				logger.logInfo("Arquivo renomeado e bloqueado para processamento: " + renamedFile.getName());
			}
		} catch (Exception e) {
			logger.logInfo("Nao conseguiu renomear o arquivo " + e.getMessage());
			return new JSONObject();
		}
		
		/*java.nio.file.Path path = java.nio.file.Paths.get("C:/TestandoFileMove");

		// File renamedFile = new File()

		// Path path2 = "C:/inout/contabil/Micalicontabil/Gabrielavec_#20/APagar";

		try {

			java.nio.file.Files.move(path, path.resolve("renamed"), java.nio.file.StandardCopyOption.REPLACE_EXISTING);

			// java.nio.file.Files.move(file2.toPath(), file2.toPath().resolve("renamed"), java.nio.file.StandardCopyOption.REPLACE_EXISTING);

			//---

			logger.logInfo("Moveu o arquvo");

			//--



		} catch (Exception e) {

			logger.logInfo("Tentou ler do diretorio ja alterado " + e.getMessage());

			return new JSONObject();

		}*/
		// File file2 = new File(jdiretorioArquivo.optString("DIRETORIO"));
		/*String path2 = "C:/inout/contabil/Micalicontabil/Gabrielavec_#20/APagar";
		if (!path2.exists()) {
			logger.logInfo("Tentou ler do diretorio ja alterado");
			return new JSONObject();
		}*/
		/*logger.logInfo("Alterou");
		File file3 = new File("C:/inout/contabil/Micalicontabil/Gabrielavec_#20/APagar"+"Renamed");
		try {
			// file2.renameTo(new File(jdiretorioArquivo.optString("DIRETORIO")+"Renamed"));
			file2.renameTo(file3);
		} catch (Exception e) {
			logger.logInfo("Erro ao renomear o arquivo " + e.getMessage());
			return new JSONObject();
		}*/
	} catch (Exception e) {
		logger.logInfo("Nao conseguiu abrir o arquivo");
		return new JSONObject();
	}
	
	try {
		
        if (jdiretorioArquivo != null && jdiretorioArquivo.has("ID")) {
			db.delete("IO_FILA")
					.where("ID = ?")
					.param(jdiretorioArquivo.optString("ID"))
					.execute();
		}
    } catch (Exception e) {
        logger.logDebug("ERRO DELETANDO DA FILA " + e.getMessage());
    }
	
	try {

		// Renomeando para o nome original

		if (renamedFile.renameTo(file2)) {

			logger.logInfo("Arquivo renomeado para o nome original: " + file2.getName());
		}
	} catch (Exception e) {
		logger.logInfo("Nao conseguiu renomear pra o nome original " + e.getMessage());
		return new JSONObject();
	}
	
	

	return jdiretorioArquivo;
}
/*
public synchronized void deleteFila(int id, DataBase db, InoutLogger logger) {
		
	try {
        db.delete("IO_FILA")
                .where("ID = ?")
                .param(id)
                .execute();
    } catch (Exception e) {
        logger.logDebug("ERRO DELETANDO DA FILA " + e.getMessage());
    }
}
*/
public void atualizaPendencias(String versaoPlataforma, String diretorioDePara, String contabilidade, File nomeArquivoDepara/* = fileDePara.getName() */, String empresa, InoutLogger logger) {
    //DE PARA
    logger.logInfo("deparing " + nomeArquivoDepara.getName());
    try {
        if(nomeArquivoDepara.getName().startsWith("OK_DePara") && nomeArquivoDepara.getName().toLowerCase().endsWith(".csv")){
                                                

            String rotaDePara = contabilidade+"DePara" + ".AtualizaPendenciasIOMovimento";
            if (versaoPlataforma.equals("02_Conecta_Via_Portal_Ottimizza")) {
                rotaDePara = "Ottimizza.AtualizaPendenciasIOMovimento";
                    
                File txtImportaPlanoContas = new File(String.format("%s/contabil/Ottimizza/AtualizaPendenciaIOMovimento/Atualiza_%s.txt", RouteEngine.INOUT_HOME, empresa));

                // Criar diretorio ottimizza/AtualizaPendenciaIOMovimento se n?o existe.
                if (!txtImportaPlanoContas.getParentFile().exists()) txtImportaPlanoContas.getParentFile().mkdirs();

                if (!txtImportaPlanoContas.exists()) {
                    try {
                        String txtIPCContent = "";

                        txtIPCContent += String.format("NOME_CONTABILIDADE : %s%n", contabilidade);
                        txtIPCContent += String.format("NOME_EMPRESA : %s%n", empresa.substring(0, empresa.indexOf("_#")));
                        txtIPCContent += String.format("CODIGO_EMPRESA : %s%n", empresa.substring(empresa.indexOf("#") + 1));

                        // Escrever texto no arquivo
                        FileWriter writerDePara = new FileWriter(txtImportaPlanoContas.getAbsolutePath());
                        writerDePara.writeNewFile(txtIPCContent);
                    } catch(Exception createFileException) {
                        logger.logError(String.format("Error trying to create file '%s'!", txtImportaPlanoContas.getAbsolutePath()), createFileException);
                    }
                } else {
                    logger.logDebug(String.format("File '%s' not created. \nThe file already exists!", txtImportaPlanoContas.getAbsolutePath()));
                }
            }

            RouteEngine.execRoute(rotaDePara);
            
            // caso encontre algum arquivo com o mesmo nome de antes de rodar a rota
            // move arquivo para pata processado para nao ficar em loop
            File fileDepoisLista = new File(diretorioDePara);
            File [] filesDepois = fileDepoisLista.listFiles();
            for (File fileDePoisComparar: filesDepois) {
                if (fileDePoisComparar.getAbsolutePath().equals(nomeArquivoDepara.getAbsolutePath()) && nomeArquivoDepara.exists()) {
                    String moveFilename = nomeArquivoDepara.getAbsolutePath();
                    moveFilename = moveFilename.replaceAll("\\\\", "/");
                    FileUtil.moveToDir(moveFilename, diretorioDePara + "/Processado");
                }
            }

        }
    } catch (Exception e) {
        logger.logError("Erro ao atualizar pendencias " + e.getMessage());
    } 
}


public void  atualizaArquivoRoteiro(String contabilidade, String empresa, InoutLogger logger) throws Exception {
	
	//logger.logDebug("Chegou 01 atualizaArquivoRoteiro");
	
	if (contabilidade.toUpperCase().equals("MICALICONTABIL") && empresa.toUpperCase().equals("TESTEGISELESEMCONVERSOR")){
		return;
	}
	
	SysProperties props  = SysProperties.getInstance();
	 // Carrega as propriedades
    props.load("contabil/" + contabilidade + "/contabil.properties");
    
	String cnpjEmpresa = props.get(empresa.toUpperCase() + "_CNPJ_EMPRESA");
	
	
    DatabasePostgreSQL postgre	= new DatabasePostgreSQL();
    DBPostgreSQL db				= null;
    DBPostgreSQL dbIntegrador	= null;
    CloudAPI cloudAPI			= new CloudAPI();

    JSONArray cnpjs				= new JSONArray();
    JSONArray roteiros		= new JSONArray();


    String tipoMov				= "";
    String rn					= "\r\n";
    String aspas				= "\"";

    SysProperties propsCont		   = SysProperties.getInstance();

    String urnExportados = "https://api-regrasoud-listener.herokuapp.com/api/v1/atualiza_roteiros/exportados";

    ConnectorConfig config = new ConnectorConfig();
    PartnerConnection connection = null;


    /* tabela: atualiza_roteiros
	campos
		BigInt - id
		Boolean - exportado
		JSON - info_roteiros -> {"idRoteiro": "a0A6R00000vgk78", "cnpjEmpresa": "92435747000190", "tipoLancamento": "1"}

	POST url: https://api-regrasoud-listener.herokuapp.com/api/v1/atualiza_roteiros/exportados
	BODY(ids da tabela atualiza_roteiros sequence) 
		[
			1,
			2
		]
    */

    try {
        // routes.properties atualizado pelo atualiza_otwpadrao
        propsCont.load("/contabil/Ottimizza/routes.properties");

        db				= DatabasePostgreSQL.connectDatabase("api-listener-exporta-roteiros", logger);
        dbIntegrador	= DatabasePostgreSQL.connectDatabase("api-integrador-contabil", logger);

        boolean conectado		= false;
        StringBuilder listaIds	= new StringBuilder();
        listaIds.append("[");

        StringBuilder lancPg		= new StringBuilder();
        StringBuilder lancRc		= new StringBuilder();
        StringBuilder jaLidos       = new StringBuilder();

        String listaIdsStr			= "";
        String codErp				= "";
        String nomeBanco			= "";
        String cnpj = "";
        String idsRoteiros = "";
		
        int contadorArquivos = 0;

        // for (MemoryFile memFile: fileLoader2.getMemFiles()) {
            // while (memFile.hasNextLine()) {

                // logger.logDebug("CNPJ EMP == "+cnpjEmpresa);
				try {
                    roteiros = postgre.buscaRoteiros(db, cnpjEmpresa, logger);
                } 
                catch(Exception ex) {
                    logger.logDebug("ERRRO buscaRoteiros -> "+ex.getMessage());
                } 

				// logger.logDebug("ROTEIROS LENGTH <> "+roteiros.length());
                if (roteiros.length() > 0) {

                  
                    for (int tt=0; tt<roteiros.length(); tt++) {

                        String roteiroString = roteiros.optJSONObject(tt).toString().replaceAll("\\\\","");
						
						logger.logDebug("Roteiro lido " + roteiroString);

                        roteiroString = roteiroString.replace("\"{","{");                 
                        roteiroString = roteiroString.replace("}\"","}"); 
                        JSONObject roteiroObj = new JSONObject(roteiroString);

                        listaIds.append(roteiroObj.optString("id")).append(",");
						
						if(!listaIds.toString().equals("[")) {
							idsRoteiros = listaIds.toString().substring(0, listaIds.toString().length() - 1)+"]";			
							try {
								cloudAPI.doPost(urnExportados, idsRoteiros);
							}
							catch (Exception xx) {
								logger.logDebug("ERROR -> "+xx.getMessage());
							}
							listaIds	= new StringBuilder();
							listaIds.append("[");							
						}
						
                        try {
                            JSONObject roteiroInfosObj = new JSONObject(roteiroObj.optString("info_roteiros").replaceAll("\\\\",""));

                            String idRoteiro       =  roteiroInfosObj.optString("idRoteiro");
                            String tipoLancamento  =  roteiroInfosObj.optString("tipoLancamento");


                            idRoteiro = cutString(idRoteiro, 0,15);
							if (idRoteiro.equals("")) {
								continue;
							}


                            if (!roteiroInfosObj.has("cnpjContabilidade")) {
								continue;
							}

                            String cnpjContabilidade  =  roteiroInfosObj.optString("cnpjContabilidade");

                            String codEmpresa		 = "";
							
                            if (jaLidos.toString().contains(idRoteiro)) {
								continue;
                            }
							
							jaLidos.append(idRoteiro).append(";");

                            if (cnpjContabilidade == null || cnpjContabilidade.equals("")) {
								continue;
							}


                            String diretorio = "";

                            String idRoteiroProperties = "";


                            try {

                                StringBuilder regrasToSF = new StringBuilder();
                                regrasToSF.append("[");
                                int contadorRegras = 0;
                                int contadorRegrasTotal = 0;

                                StringBuilder historicosToSF = new StringBuilder();
                                historicosToSF.append("[");
                                int contadorHistoricos = 0;
                                int contadorHistoricosTotal = 0;
								
								String licencaProduto = "";
								
								logger.logDebug("CC " + cnpjContabilidade + " | " + cnpjEmpresa);
								
								try {
									// contabilidade	= toDisplayCase(propsCont.get(cnpjContabilidade));
									props.load("/contabil/" + contabilidade + "/contabil.properties");
									empresa	= props.get(cnpjEmpresa);             
									codEmpresa = props.get(empresa.toUpperCase() + "_COD_EMPRESA");
									idRoteiroProperties = props.get(empresa.toUpperCase() + "_ID_ROTEIRO_PAGAR");
									idRoteiroProperties = idRoteiroProperties + ";" +  props.get(empresa.toUpperCase() + "_ID_ROTEIRO_RECEBER");
 									licencaProduto      = props.get(empresa.toUpperCase() + "_TIPO_PRODUTO"); 
									 
								} catch (Exception xx) {
									logger.logDebug("erro props " + xx.getMessage() + " | " + contabilidade + "--" + codEmpresa + "--" + empresa);
									continue;
								}

                                //EXPORTACAO DE HISTORICOS PARA O SALESFORCE

                                JSONArray historicos = buscaHistoricos(cnpjContabilidade, cnpjEmpresa, tipoLancamento, dbIntegrador, logger);
                                for(int h = 0; h < historicos.length(); h++) {
                                    try {
                                        JSONObject historico = historicos.optJSONObject(h);
                                        String idExternoHistorico = historico.optString("id");
                                        String contaMovimentoHistorico = historico.optString("contaMovimento");
                                        String historicoCompleto = historico.optString("historico");
                                        String grupoRegraId = historico.optString("grupoRegraId");

                                        String codigoHistorico = "";
                                        String texto01 = "";
                                        String campoHistorico01 = "";
                                        String texto02 = "";
                                        String campoHistorico02 = "";
                                        String texto03 = "";
                                        String campoHistorico03 = "";
                                        String texto04 = "";
                                        String campoHistorico04 = "";
                                        String texto05 = "";
                                        String campoHistorico05 = "";

                                        JSONObject historicoSf = new JSONObject();	
                                        if(grupoRegraId != null && !grupoRegraId.equals("")) {

                                            JSONArray regrasBd = buscaRegrasPorGrupoRegraId(grupoRegraId, dbIntegrador, logger);
                                            JSONArray regras = new JSONArray();
                                            for(int r = 0; r < regrasBd.length(); r++) {
                                                String campo = regrasBd.optJSONObject(r).optString("campo");
                                                if(!campo.contains("tipoMovimento")) 
                                                    regras.put(regrasBd.optJSONObject(r));
                                            }

                                            if(regras.length() > 0)
                                                historicoSf = criaHistoricoSfPorRegra(historico, regras, logger);
                                            else {
                                                try{ 
                                                    historicoSf = criaHistoricoSf(historico, logger);
                                                }
                                                catch(Exception ex) { 
                                                    logger.logDebug("Error transformando historico para Salesforce -> "+ex.getMessage()); 
                                                    contadorHistoricosTotal++; 
                                                    continue;
                                                }
                                            }
                                        }
                                        else {
                                            try{ 
                                                historicoSf = criaHistoricoSf(historico, logger);
                                            }
                                            catch(Exception ex) { 
                                                logger.logDebug("Error transformando historico para Salesforce -> "+ex.getMessage()); 
                                                contadorHistoricosTotal++; 
                                                continue;
                                            }
                                        }

                                        historicoSf.put("Roteiro__c", idRoteiro);
                                        historicosToSF.append(historicoSf.toString()).append(",");
                                        contadorHistoricos++;
                                        contadorHistoricosTotal++; 

                                        if(contadorHistoricos == 200 || contadorHistoricosTotal == historicos.length()) {
                                            historicosToSF.append("]");
                                            contadorHistoricos = 0;

                                            String dirName = RouteEngine.INOUT_HOME +"/contabil/Ottimizza/EnvioHisotricoSalesforce/arquivo_"+idRoteiro+"_"+String.valueOf(tt) + ".txt";
                                            FileWriter txtHistoricos = new FileWriter(dirName);
                                            txtHistoricos.writeNewFile(historicosToSF.toString()); 
                                            RouteEngine.execRoute("Ottimizza.AtualizaHistoricosOUDnoSalesforce");

                                            historicosToSF = new StringBuilder();
                                            historicosToSF.append("[");
                                        }
                                    }
                                    catch(Exception ex) {
                                        logger.logDebug("EXCEPTION HISTORICOS -> "+ex.getMessage());
                                        continue;
                                    }
                                }
                            }
                            catch (Exception xx) {
                                logger.logDebug("ERROR -> "+xx.getMessage());
                            } 


                             



                            if (!idRoteiroProperties.contains(idRoteiro)){
							
								JSONObject roteiroLog = new JSONObject(roteiroString);
								roteiroLog.put("Erro","ErroID");  
								roteiroLog.put("Contabilidade",contabilidade);
								roteiroLog.put("Empresa",empresa);
								roteiroLog.put("ID Properties",idRoteiroProperties);
								roteiroLog.put("IdRoteiro", idRoteiro);
								
								continue;
							}
							
							
							// aguarda um segundo para dar tempo das regras estarem salvas no salesforce.
							Thread.sleep(1000);

								
							if (connection == null) {
								config.setUsername("fabrica@ottimizza.com.br");
								config.setPassword("ottimizza@123HU4ssqt1HCiLyCzj6QStgteM2");
								config.setTraceMessage(false);
								connection = Connector.newConnection(config);  
							}	
                             


                            if (tipoLancamento.equals("1"))  preparaArquivo40(idRoteiro, "Contas PAGAS", contabilidade, empresa, "", "", connection, logger);
                            if (tipoLancamento.equals("2"))  preparaArquivo40(idRoteiro, "Contas RECEBIDAS", contabilidade, empresa, "", "", connection, logger);
                            if (tipoLancamento.equals("1"))  preparaArquivoEspecifico40(idRoteiro, "Contas PAGAS", contabilidade, empresa, "", "", connection, logger);
                            if (tipoLancamento.equals("2"))  preparaArquivoEspecifico40(idRoteiro, "Contas RECEBIDAS", contabilidade, empresa, "", "", connection, logger);



                        }
                        catch (Exception xx) {
                            logger.logDebug("ERROR -> "+xx.getMessage());
                        }
                    }

                }
            // }
            if(!listaIds.toString().equals("[")) {
                idsRoteiros = listaIds.toString().substring(0, listaIds.toString().length() - 1)+"]";			
                try {
                    cloudAPI.doPost(urnExportados, idsRoteiros);
                }
                catch (Exception xx) {
                    logger.logDebug("ERROR -> "+xx.getMessage());
                }                    
            }
        // }	


    } catch (Exception e) {
        logger.logDebug("*** por algum motivo cai no catch geral da rota -> "+e.getMessage());
    } finally {
        if (db != null) db.closeConnection();
		if (dbIntegrador != null) dbIntegrador.closeConnection();
		
    }
	
	logger.logDebug("Terminou 01 atualizaArquivoRoteiro");
 	
}

public void preparaArquivo40(String idRoteiro, String tipoIntegracao, String contabilidade, String empresa, String dirName, String dirNameW, PartnerConnection connection, InoutLogger logger) {
	try {
        StringBuilder codigoNovo    = new StringBuilder();
        StringBuilder codigoRoteiro = new StringBuilder();


        try {
            String tipoRoteiro = "_ContasPagasRoteiroPadrao.script";
            if (tipoIntegracao.toUpperCase().contains("RECE")) tipoRoteiro = "_ContasRecebidasRoteiroPadrao.script";
            File fileRoteiro = new File("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);

            codigoRoteiro.append(prepareScript(idRoteiro, "OTTPADRAO" + empresa, "", contabilidade, tipoIntegracao, connection, logger));


            if (!codigoRoteiro.toString().equals("")) {
                logger.logDebug("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);

                FileWriter writer = new FileWriter("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
                writer.writeNewFile(codigoRoteiro.toString());			


            }	


        } catch (Exception xx) {logger.logDebug("XX " + xx);}


    }


    catch (Exception xx) {}

    return;
}



public void preparaArquivoEspecifico40(String idRoteiro, String tipoIntegracao, String contabilidade, String empresa, String dirName, String dirNameW, PartnerConnection connection, InoutLogger logger) {
	try {
        StringBuilder codigoNovo    = new StringBuilder();
        StringBuilder codigoRoteiro = new StringBuilder();


        try {
            String tipoRoteiro = "_ContasPagasRoteiro.script";
            if (tipoIntegracao.toUpperCase().contains("RECE")) tipoRoteiro = "_ContasRecebidasRoteiro.script";
            File fileRoteiro = new File("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);

            codigoRoteiro.append(prepareScript(idRoteiro, "OTTPADRAO" + empresa, "", contabilidade, tipoIntegracao, connection, logger));


            if (!codigoRoteiro.toString().equals("")) {
                logger.logDebug("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);

                FileWriter writer = new FileWriter("c:/ottimizza/dropbox/deploy/routes/" + contabilidade + "/" + empresa + tipoRoteiro);
                writer.writeNewFile(codigoRoteiro.toString());			


            }	


        } catch (Exception xx) {logger.logDebug("XX " + xx);}

	}


    catch (Exception xx) {}

    return;
}

public String trataCampoHistorico(String campo) throws Exception {
    if(campo.contains("descricao")) {
        campo = "Fornecedor/Cliente";
    }
    if(campo.contains("portador")) {
        campo = "Portador";
    }
    if(campo.contains("competencia")) {
        if(campo.contains("Anterior"))
            campo = "Mes-Ano Anterior";
        else
            campo = "Mes-Ano Atual";
    }
    if(campo.contains("documento")) {
        campo = "Documento/NF";
    }
    if (campo.contains("complemento")) {
        campo = campo.replaceFirst("c", "C").replace("o0", "o (0").concat(")");
    }
    if(campo.contains("nenhum")) {
        campo = "";
    }
    return campo;
}

public String trataCampoRegra(String campo, int condicao) {

    if (campo.contains("complemento")) {
        campo = campo.replaceFirst("c", "C").replace("o0", "o (0").concat(")");
    }
    else if (campo.contains("tipoPlanilha")) {
        campo = "Tipo Planilha";
    }
    else if (campo.contains("portador")) {
        campo = "Portador";
    }
    else if (campo.contains("descricao")) {
        campo = "Fornecedor/Cliente";
    }
    else if (campo.contains("documento")) {
        campo = "Documento/NF";
    }
    else if(campo.contains("nomeArquivo")) {
        campo = "Nome do Arquivo";
    }

    //TRATANDO CONDICAO 

    if(condicao == 1) {
        campo = campo.concat(" cont" + (char)233 + "m");
    }
    else if(condicao == 2) {
        campo = campo.concat(" n" + (char)227 + "o " + "cont" + (char)233 + "m");
    }
    else if(condicao == 3) {
        campo = campo.concat(" come" + (char)231 + "a com");
    }
    else if(condicao == 4) {
        campo = campo.concat(" igual a");
    }
    return campo;

}


public JSONArray buscaRegrasPorGrupoRegraId(String grupoRegraId, DBPostgreSQL db, InoutLogger logger) throws SQLException {
    String sql = "select campo as campo, condicao as condicao, valor as valor "
    + "from regras r "
    + "where fk_grupo_regras_id = "+grupoRegraId+" ";			
    try {
        JSONArray records = db.sql(sql)
        .setFields("campo, condicao,  valor")
        .debug(logger)
        .query();

        return records;

    } catch (Exception e) {
        logger.logDebug("ERROR buscaRegrasPorGrupoRegraId: "+e.getMessage());
    }
    return null;
}

public JSONArray buscaGrupoRegras(String cnpjContabilidade, String cnpjEmpresa, String tipoLancamento, DBPostgreSQL db, InoutLogger logger) throws SQLException {
	//String currentDate = "'" + DateUtil.dateToString(new Date(), "yyyy-MM-dd 00:00:00") + "'";
	Calendar cal = Calendar.getInstance();
    try {
		cal = DateUtil.dateToCalendar(new Date());
		cal.add(Calendar.DATE, -30);
    } catch (Exception e) {
        logger.logDebug("ERROR buscaGrupoRegras add date: "+e.getMessage());
    }
	String currentDate = "'" + DateUtil.dateToString(cal.getTime(), "yyyy-MM-dd 00:00:00") + "'";
	
    String sql = "select id as id, conta_movimento as contaMovimento, id_roteiro as idRoteiro, posicao as posicao, conta_desconto as contaDesconto, "
    + "conta_juros as contaJuros, conta_multa as contaMulta, conta_portador as contaPortador, inverte_contas as inverteContas "
    + "from grupo_regras gr "					
    + "where gr.cnpj_empresa = '"+cnpjEmpresa+"' "
    + "and gr.cnpj_contabilidade = '"+cnpjContabilidade+"' "
    + "and gr.tipo_lancamento = "+tipoLancamento+" "
    + "and gr.ativo = true "
	+ "and gr.data_atualizacao >= " + currentDate + "::date "
    + "and (SELECT COUNT(r.id) FROM regras r WHERE r.fk_grupo_regras_id = gr.id) > 0 "
    + "order by gr.posicao asc ";			

    try {
        JSONArray records = db.sql(sql)
        .setFields("id, contaMovimento, idRoteiro, posicao, contaDesconto, contaJuros, contaMulta, contaPortador, inverteContas")
        .debug(logger)
        .query();
        return records;

    } catch (Exception e) {
        logger.logDebug("ERROR buscaGrupoRegras: "+e.getMessage());
    }
    return null;
}

public JSONArray buscaHistoricos(String cnpjContabilidade, String cnpjEmpresa, String tipoLancamento, DBPostgreSQL db, InoutLogger logger) throws SQLException {
	//String currentDate = "'" + DateUtil.dateToString(new Date(), "yyyy-MM-dd 00:00:00") + "'";
	Calendar cal = Calendar.getInstance();
    try {
		cal = DateUtil.dateToCalendar(new Date());
		cal.add(Calendar.DATE, -30);
    } catch (Exception e) {
        logger.logDebug("ERROR buscaHistoricos add date: "+e.getMessage());
    }
	String currentDate = "'" + DateUtil.dateToString(cal.getTime(), "yyyy-MM-dd 00:00:00") + "'";
	
    String sql = "SELECT id as id, conta_movimento as contaMovimento, historico as historico, id_roteiro as idRoteiro, fk_grupo_regras_id as grupoRegraId, historico_padrao as historicoPadrao "
    + "FROM historicos h "
    + "WHERE h.cnpj_contabilidade = '"+cnpjContabilidade+"' "
    + "and h.cnpj_empresa = '"+cnpjEmpresa+"' "
    + "and h.tipo_lancamento = "+tipoLancamento+" "
    + "and h.ativo = true "
	+ "and h.data_atualizacao >= " + currentDate + "::date ";

    try {
        JSONArray records = db.sql(sql)
        .setFields("id, contaMovimento, historico, idRoteiro, grupoRegraId, historicoPadrao")
        .debug(logger)
        .query();

        
		// logger.logDebug("HST RECORDS -> "+records.toString());
		return records;

    } catch (Exception e) {
        logger.logDebug("ERROR buscaHistoricos: "+e.getMessage());
    }
    return null;
}


public JSONObject criaHistoricoSfPorRegra(JSONObject historico, JSONArray regras, InoutLogger logger) throws Exception {
    try{

        String idExternoHistorico = historico.optString("id");
        String historicoCompleto = historico.optString("historico");
        String[] historicoArray = historicoCompleto.split("\\$");
        String codigoHistorico = historicoArray[0].replace("CodigoHistorico:", "").trim();

        int condicao01 = regras.optJSONObject(0).optInt("condicao");
        String campoRegra01 = trataCampoRegra(regras.optJSONObject(0).optString("campo"), condicao01);
        String valor01 = regras.optJSONObject(0).optString("valor");
        String campoRegra02 = " ";
        String valor02 = " ";
        int condicao02 = 1;
        String campoRegra03 = " ";
        String valor03 = " ";
        int condicao03 = 1;
        String campoRegra04 = " ";
        String valor04 = " ";
        int condicao04 = 1;
        String campoRegra05 = " ";
        String valor05 = " ";
        int condicao05 = 1;
        String sequenciaRegras = "110";
        String texto01 = "";
        String campoHistorico01 = "";
        String texto02 = "";
        String campoHistorico02 = "";
        String texto03 = "";
        String campoHistorico03 = "";
        String texto04 = "";
        String campoHistorico04 = "";
        String texto05 = "";
        String campoHistorico05 = "";


        if(regras.length() > 1) {
            condicao02 = regras.optJSONObject(1).optInt("condicao");
            campoRegra02 = trataCampoRegra(regras.optJSONObject(1).optString("campo"), condicao02);
            valor02 = regras.optJSONObject(1).optString("valor");
            sequenciaRegras = "200";
        }
        if(regras.length() > 2) {
            condicao03 = regras.optJSONObject(2).optInt("condicao");
            campoRegra03 = trataCampoRegra(regras.optJSONObject(2).optString("campo"), condicao03);
            valor03 = regras.optJSONObject(2).optString("valor");
            sequenciaRegras = "300";
        }
        if(regras.length() > 3 ) {
            condicao04 = regras.optJSONObject(3).optInt("condicao");
            campoRegra04 = trataCampoRegra(regras.optJSONObject(3).optString("campo"), condicao04);
            valor04 = regras.optJSONObject(3).optString("valor");
            sequenciaRegras = "400";
        }
        if(regras.length() > 4) {
            condicao05 = regras.optJSONObject(4).optInt("condicao");
            campoRegra05 = trataCampoRegra(regras.optJSONObject(4).optString("campo"), condicao05);
            valor05 = regras.optJSONObject(4).optString("valor");
            sequenciaRegras = "500";
        }

        if(historicoArray.length > 1)
            texto01 = historicoArray[1].trim();
        if(historicoArray.length > 2) {
            campoHistorico01 = historicoArray[2].substring(historicoArray[2].indexOf("{")+1,historicoArray[2].indexOf("}"));
            texto02 = historicoArray[2].substring(historicoArray[2].indexOf("}")+1);
        }
        if(historicoArray.length > 3) {
            campoHistorico02 = historicoArray[3].substring(historicoArray[3].indexOf("{")+1,historicoArray[3].indexOf("}"));
            texto03 = historicoArray[3].substring(historicoArray[3].indexOf("}")+1);
        }
        if(historicoArray.length > 4) {
            campoHistorico03 = historicoArray[4].substring(historicoArray[4].indexOf("{")+1,historicoArray[4].indexOf("}"));
            texto04 = historicoArray[4].substring(historicoArray[4].indexOf("}")+1);
        }
        if(historicoArray.length > 5) {
            campoHistorico04 = historicoArray[5].substring(historicoArray[5].indexOf("{")+1,historicoArray[5].indexOf("}"));
            texto05 = historicoArray[5].substring(historicoArray[5].indexOf("}")+1);
        }
        if(historicoArray.length > 6) 
            campoHistorico05 = historicoArray[6].substring(historicoArray[6].indexOf("{")+1,historicoArray[6].indexOf("}"));

        JSONObject historicoSf = new JSONObject();
        historicoSf.put("RecordTypeId","0121500000100GB");
        historicoSf.put("ID_Externo__c", idExternoHistorico.replaceAll("\\.00", ""));
        historicoSf.put("Codigo_Historico__c", codigoHistorico);
        historicoSf.put("Se_Campo__c", campoRegra01);
        historicoSf.put("O_texto_01__c", valor01);
        historicoSf.put("E_02__c", campoRegra02);
        historicoSf.put("O_texto_02__c", valor02);
        historicoSf.put("E_03__c", campoRegra03);
        historicoSf.put("O_texto_03__c", valor03);
        historicoSf.put("E_04__c", campoRegra04);
        historicoSf.put("O_texto_04__c", valor04);
        historicoSf.put("E_05__c", campoRegra05);
        historicoSf.put("O_texto_05__c", valor05);
        historicoSf.put("Texto_01__c", texto01);
        historicoSf.put("Campo_01__c", trataCampoHistorico(campoHistorico01));
        historicoSf.put("Texto_02__c", texto02);
        historicoSf.put("Campo_02__c", trataCampoHistorico(campoHistorico02));
        historicoSf.put("Texto_03__c", texto03);
        historicoSf.put("Campo_03__c", trataCampoHistorico(campoHistorico03));
        historicoSf.put("Texto_04__c", texto04);
        historicoSf.put("Campo_04__c", trataCampoHistorico(campoHistorico04));
        historicoSf.put("Texto_05__c", texto05);
        historicoSf.put("Campo_05__c", trataCampoHistorico(campoHistorico05));
        historicoSf.put("Sequencia_das_Regras__c", sequenciaRegras);
        return historicoSf;
    }
    catch(Exception ex) {
        logger.logDebug("ERROR CRIACAO HISTORICO SALESFORCE POR REGRA -> "+ex.getMessage());
        return null;
    }
}

public JSONObject criaHistoricoSf(JSONObject historico, InoutLogger logger) throws Exception {
    try{
        String idExternoHistorico = historico.optString("id");
        String contaMovimentoHistorico = historico.optString("contaMovimento");
        String historicoCompleto = historico.optString("historico");
		boolean historicoPadrao = false;
		if(historico.has("historicoPadrao") && historico.optString("historicoPadrao").toUpperCase().equals("TRUE")) {
			historicoPadrao = true;
		}

        String codigoHistorico = "";
        String texto01 = "";
        String campoHistorico01 = "";
        String texto02 = "";
        String campoHistorico02 = "";
        String texto03 = "";
        String campoHistorico03 = "";
        String texto04 = "";
        String campoHistorico04 = "";
        String texto05 = "";
        String campoHistorico05 = "";

        String[] historicoArray = historicoCompleto.split("\\$");
        codigoHistorico = historicoArray[0].replace("CodigoHistorico:", "").trim();
        if(historicoArray.length > 1)
            texto01 = historicoArray[1].trim();
        if(historicoArray.length > 2) {
            campoHistorico01 = historicoArray[2].substring(historicoArray[2].indexOf("{")+1,historicoArray[2].indexOf("}"));
            texto02 = historicoArray[2].substring(historicoArray[2].indexOf("}")+1);
        }
        if(historicoArray.length > 3) {
            campoHistorico02 = historicoArray[3].substring(historicoArray[3].indexOf("{")+1,historicoArray[3].indexOf("}"));
            texto03 = historicoArray[3].substring(historicoArray[3].indexOf("}")+1);
        }
        if(historicoArray.length > 4) {
            campoHistorico03 = historicoArray[4].substring(historicoArray[4].indexOf("{")+1,historicoArray[4].indexOf("}"));
            texto04 = historicoArray[4].substring(historicoArray[4].indexOf("}")+1);
        }
        if(historicoArray.length > 5) {
            campoHistorico04 = historicoArray[5].substring(historicoArray[5].indexOf("{")+1,historicoArray[5].indexOf("}"));
            texto05 = historicoArray[5].substring(historicoArray[5].indexOf("}")+1);
        }
        if(historicoArray.length > 6) 
            campoHistorico05 = historicoArray[6].substring(historicoArray[6].indexOf("{")+1,historicoArray[6].indexOf("}"));

        JSONObject historicoSf = new JSONObject();
        historicoSf.put("RecordTypeId","0121500000100GB");
		historicoSf.put("Sequencia_das_Regras__c", "500");
        historicoSf.put("ID_Externo__c", idExternoHistorico.replaceAll("\\.00", ""));
        historicoSf.put("Codigo_Historico__c", codigoHistorico);
        historicoSf.put("Se_Campo__c", "Conta Normal - Movimento - igual a ");
        historicoSf.put("O_texto_01__c", contaMovimentoHistorico);
        historicoSf.put("Texto_01__c", texto01);
        historicoSf.put("Campo_01__c", trataCampoHistorico(campoHistorico01));
        historicoSf.put("Texto_02__c", texto02);
        historicoSf.put("Campo_02__c", trataCampoHistorico(campoHistorico02));
        historicoSf.put("Texto_03__c", texto03);
        historicoSf.put("Campo_03__c", trataCampoHistorico(campoHistorico03));
        historicoSf.put("Texto_04__c", texto04);
        historicoSf.put("Campo_04__c", trataCampoHistorico(campoHistorico04));
        historicoSf.put("Texto_05__c", texto05);
        historicoSf.put("Campo_05__c", trataCampoHistorico(campoHistorico05));
		
		// VALIDANDO SE E UM HISTORICO PADRAO
		if(historicoPadrao == true) {
			if(idExternoHistorico.contains("903117"))
				logger.logDebug("Historico -> "+historico);
			historicoSf.put("Sequencia_das_Regras__c", "100");
			historicoSf.put("Se_Campo__c", "Fornecedor/Cliente n" + (char)227 + "o cont" + (char)233 + "m");
			historicoSf.put("O_texto_01__c", "HISTORICOPADRAO");
		}
		
        return historicoSf;
    }
    catch(Exception ex) {
        logger.logDebug("ERROR CRIACAO HISTORICO SALESFORCE -> "+ex.getMessage());
        return null;
    }
}